using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Windows.Forms.Layout;
using MusicTag.Composer;
using MusicTag.Consumers;
using MusicTag.Importers;
using MusicTag.Mocks;
using MusicTag.Readers;
using MusicTag.Schemes;
using MusicTag.Serialization;
using MusicTag.Services;
using MusicTag.States;
using MusicTagWinApp.Adapter;
using MusicTagWinApp.Common;
using MusicTagWinApp.Containers;
using MusicTagWinApp.Exporters;
using MusicTagWinApp.Listeners;
using MusicTagWinApp.Properties;
using MusicTagWinApp.Roles;
using MusicTagWinApp.Structs;
using MusicTagWinApp.Web;
using Newtonsoft.Json;

namespace MusicTagWinApp.Instances;

internal partial class StateFieldInstance
{
	private void InitializeComponent()
	{
		components = new System.ComponentModel.Container();
		ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(StateFieldInstance));
		mainMenuStrip = new MenuStrip();
		fileMenuItem = new ToolStripMenuItem();
		changeDirectoryMenuItem = new ToolStripMenuItem();
		addDirectoryMenuItem = new ToolStripMenuItem();
		manageDirectoriesMenuItem = new ToolStripMenuItem();
		fileMenuTagActionsSeparator = new ToolStripSeparator();
		saveTagsMenuItem = new ToolStripMenuItem();
		removeTagsMenuItem = new ToolStripMenuItem();
		readTagsMenuItem = new ToolStripMenuItem();
		characterSetMenuItem = new ToolStripMenuItem();
		chineseConversionMenuItem = new ToolStripMenuItem();
		convertTagsTraditionalToSimplifiedMenuItem = new ToolStripMenuItem();
		convertTagsSimplifiedToTraditionalMenuItem = new ToolStripMenuItem();
		tagHistoryMenuItem = new ToolStripMenuItem();
		fileMenuExitSeparator = new ToolStripSeparator();
		exitMenuItem = new ToolStripMenuItem();
		editMenuItem = new ToolStripMenuItem();
		selectAllFilesMenuItem = new ToolStripMenuItem();
		unselectAllFilesMenuItem = new ToolStripMenuItem();
		invertFileSelectionMenuItem = new ToolStripMenuItem();
		editSelectionSeparator = new ToolStripSeparator();
		undoMenuItem = new ToolStripMenuItem();
		renameFileMenuItem = new ToolStripMenuItem();
		removeItemsMenuItem = new ToolStripMenuItem();
		removeFilesMenuItem = new ToolStripMenuItem();
		openDirectoryMenuItem = new ToolStripMenuItem();
		viewMenuItem = new ToolStripMenuItem();
		refreshMenuItem = new ToolStripMenuItem();
		customizeColumnsMenuItem = new ToolStripMenuItem();
		tagSourcesMenuItem = new ToolStripMenuItem();
		coverSourceMenuItem = new ToolStripMenuItem();
		defaultCoverSourceMenuItem = new ToolStripMenuItem();
		lyricSourceMenuItem = new ToolStripMenuItem();
		defaultLyricSourceMenuItem = new ToolStripMenuItem();
		combinedTagSourceMenuItem = new ToolStripMenuItem();
		defaultCombinedTagSourceMenuItem = new ToolStripMenuItem();
		batchMenuItem = new ToolStripMenuItem();
		batchAutoMatchTagsMenuItem = new ToolStripMenuItem();
		batchLyricMenuItem = new ToolStripMenuItem();
		reformatLyricTimeTagsMenuItem = new ToolStripMenuItem();
		removeLyricTimeTagsMenuItem = new ToolStripMenuItem();
		deleteBlankLyricLinesMenuItem = new ToolStripMenuItem();
		deleteLyricHeaderTagsMenuItem = new ToolStripMenuItem();
		saveLyricsMenuItem = new ToolStripMenuItem();
		importLrcFilesMenuItem = new ToolStripMenuItem();
		batchExtractCoverMenuItem = new ToolStripMenuItem();
		batchFilenameRelatedMenuItem = new ToolStripMenuItem();
		batchChineseConversionMenuItem = new ToolStripMenuItem();
		batchTagsTraditionalToSimplifiedMenuItem = new ToolStripMenuItem();
		batchTagsSimplifiedToTraditionalMenuItem = new ToolStripMenuItem();
		batchFilenameTraditionalToSimplifiedMenuItem = new ToolStripMenuItem();
		batchFilenameSimplifiedToTraditionalMenuItem = new ToolStripMenuItem();
		toolsMenuItem = new ToolStripMenuItem();
		optionsMenuItem = new ToolStripMenuItem();
		languageMenuItem = new ToolStripMenuItem();
		englishLanguageMenuItem = new ToolStripMenuItem();
		simplifiedChineseLanguageMenuItem = new ToolStripMenuItem();
		traditionalChineseLanguageMenuItem = new ToolStripMenuItem();
		helpMenuItem = new ToolStripMenuItem();
		checkForUpdatesMenuItem = new ToolStripMenuItem();
		musicTagWebsiteMenuItem = new ToolStripMenuItem();
		aboutMenuItem = new ToolStripMenuItem();
		mainToolStrip = new ToolStrip();
		changeDirectoryToolStripButton = new ToolStripButton();
		addDirectoriesToolStripButton = new ToolStripButton();
		manageDirectoriesToolStripButton = new ToolStripButton();
		directoryToolbarSeparator = new ToolStripSeparator();
		saveTagsToolStripButton = new ToolStripButton();
		removeTagsToolStripButton = new ToolStripButton();
		undoToolStripButton = new ToolStripButton();
		readTagsToolStripButton = new ToolStripButton();
		characterSetToolStripButton = new ToolStripButton();
		chineseConversionToolStripDropDownButton = new ToolStripDropDownButton();
		convertTagsTraditionalToSimplifiedToolStripMenuItem = new ToolStripMenuItem();
		convertTagsSimplifiedToTraditionalToolStripMenuItem = new ToolStripMenuItem();
		tagHistoryToolStripButton = new ToolStripButton();
		tagActionsToolbarSeparator = new ToolStripSeparator();
		selectAllFilesToolStripButton = new ToolStripButton();
		unselectAllFilesToolStripButton = new ToolStripButton();
		selectionToolbarSeparator = new ToolStripSeparator();
		refreshToolStripButton = new ToolStripButton();
		sourceToolbarSeparator = new ToolStripSeparator();
		coverSourceToolStripSplitButton = new ToolStripSplitButton();
		lyricSourceToolStripSplitButton = new ToolStripSplitButton();
		combinedTagSourceToolStripSplitButton = new ToolStripSplitButton();
		batchToolbarStartSeparator = new ToolStripSeparator();
		batchAutoMatchTagsToolStripButton = new ToolStripButton();
		batchSaveAsLrcToolStripSplitButton = new ToolStripSplitButton();
		reformatLyricTimeTagsToolStripMenuItem = new ToolStripMenuItem();
		removeLyricTimeTagsToolStripMenuItem = new ToolStripMenuItem();
		deleteBlankLyricLinesToolStripMenuItem = new ToolStripMenuItem();
		deleteLyricHeaderTagsToolStripMenuItem = new ToolStripMenuItem();
		importLrcFilesToolStripMenuItem = new ToolStripMenuItem();
		batchExtractCoverToolStripButton = new ToolStripButton();
		batchChineseConversionToolStripDropDownButton = new ToolStripDropDownButton();
		batchTagsTraditionalToSimplifiedToolStripMenuItem = new ToolStripMenuItem();
		batchTagsSimplifiedToTraditionalToolStripMenuItem = new ToolStripMenuItem();
		batchFilenameTraditionalToSimplifiedToolStripMenuItem = new ToolStripMenuItem();
		batchFilenameSimplifiedToTraditionalToolStripMenuItem = new ToolStripMenuItem();
		batchFilenameRelatedToolStripButton = new ToolStripButton();
		batchToolbarOptionsSeparator = new ToolStripSeparator();
		optionsToolStripButton = new ToolStripButton();
		localCoverFileDialog = new OpenFileDialog();
		coverContextMenu = new ContextMenuStrip(components);
		addCoverMenuItem = new ToolStripMenuItem();
		chooseLocalCoverMenuItem = new ToolStripMenuItem();
		searchCoverFromNetworkMenuItem = new ToolStripMenuItem();
		chooseCoverFromTagsMenuItem = new ToolStripMenuItem();
		changeCoverResolutionMenuItem = new ToolStripMenuItem();
		removeCoverMenuItem = new ToolStripMenuItem();
		openCoverMenuItem = new ToolStripMenuItem();
		extractCoverMenuItem = new ToolStripMenuItem();
		coverContextMenuSeparator = new ToolStripSeparator();
		coverTypeMenuItem = new ToolStripMenuItem();
		extractCoverSaveFileDialog = new SaveFileDialog();
		controlToolTip = new ToolTip(components);
		titleEncodingButton = new Button();
		artistEncodingButton = new Button();
		albumEncodingButton = new Button();
		yearEncodingButton = new Button();
		trackEncodingButton = new Button();
		discEncodingButton = new Button();
		genreEncodingButton = new Button();
		albumArtistEncodingButton = new Button();
		composerEncodingButton = new Button();
		lyricistEncodingButton = new Button();
		commentEncodingButton = new Button();
		editLyricsButton = new Button();
		lyricsEncodingButton = new Button();
		overwriteCoverCheckBox = new CheckBox();
		fileListHeaderContextMenu = new ContextMenuStrip(components);
		customizeColumnsContextMenuItem = new ToolStripMenuItem();
		fileListItemContextMenu = new ContextMenuStrip(components);
		saveTagsContextMenuItem = new ToolStripMenuItem();
		removeTagsContextMenuItem = new ToolStripMenuItem();
		readTagsContextMenuItem = new ToolStripMenuItem();
		characterSetContextMenuItem = new ToolStripMenuItem();
		tagHistoryContextMenuItem = new ToolStripMenuItem();
		fileListItemContextSeparator = new ToolStripSeparator();
		renameFileContextMenuItem = new ToolStripMenuItem();
		removeItemsContextMenuItem = new ToolStripMenuItem();
		removeFilesContextMenuItem = new ToolStripMenuItem();
		openDirectoryContextMenuItem = new ToolStripMenuItem();
		selectionStatusUpdateTimer = new System.Windows.Forms.Timer(components);
		fileListStatusTimer = new System.Windows.Forms.Timer(components);
		filterInputTimer = new System.Windows.Forms.Timer(components);
		renamedFilesRefreshTimer = new System.Windows.Forms.Timer(components);
		comboBoxSelectionResetTimer = new System.Windows.Forms.Timer(components);
		notifyIcon = new NotifyIcon(components);
		notifyContextMenu = new ContextMenuStrip(components);
		notifyExitMenuItem = new ToolStripMenuItem();
		mainSplitContainer = new DoubleBufferedSplitContainer();
		tagEditorPanel = new FlowLayoutPanel();
		titleLabel = new Label();
		titleRowPanel = new FlowLayoutPanel();
		titleComboBox = new ComboBox();
		artistLabel = new Label();
		artistRowPanel = new FlowLayoutPanel();
		artistComboBox = new ComboBox();
		albumLabel = new Label();
		albumRowPanel = new FlowLayoutPanel();
		albumComboBox = new ComboBox();
		yearLabel = new Label();
		yearRowPanel = new FlowLayoutPanel();
		yearComboBox = new ComboBox();
		trackDiscGroupPanel = new FlowLayoutPanel();
		trackColumnPanel = new FlowLayoutPanel();
		trackLabel = new Label();
		trackRowPanel = new FlowLayoutPanel();
		trackComboBox = new ComboBox();
		discColumnPanel = new FlowLayoutPanel();
		discLabel = new Label();
		discRowPanel = new FlowLayoutPanel();
		discComboBox = new ComboBox();
		genreLabel = new Label();
		genreRowPanel = new FlowLayoutPanel();
		genreComboBox = new ComboBox();
		albumArtistLabel = new Label();
		albumArtistRowPanel = new FlowLayoutPanel();
		albumArtistComboBox = new ComboBox();
		composerLabel = new Label();
		composerRowPanel = new FlowLayoutPanel();
		composerComboBox = new ComboBox();
		lyricistLabel = new Label();
		lyricistRowPanel = new FlowLayoutPanel();
		lyricistComboBox = new ComboBox();
		commentLabel = new Label();
		commentRowPanel = new FlowLayoutPanel();
		commentComboBox = new ComboBox();
		lyricsLabel = new Label();
		lyricsRowPanel = new FlowLayoutPanel();
		lyricsComboBox = new ComboBox();
		coverPanel = new FlowLayoutPanel();
		coverPictureBox = new PictureBox();
		statusLabelsPanel = new FlowLayoutPanel();
		coverMimeTypeLabel = new Label();
		coverDimensionsLabel = new Label();
		coverFileSizeLabel = new Label();
		coverPictureTypeLabel = new Label();
		coverNavigationPanel = new FlowLayoutPanel();
		previousCoverButton = new Button();
		coverIndexLabel = new Label();
		nextCoverButton = new Button();
		tagEditorBottomSpacerPanel = new Panel();
		fileListView = new BufferedDataGridView();
		fileFilterStatusStrip = new StatusStrip();
		filterStatusLabel = new ToolStripStatusLabel();
		filterTextBox = new ToolStripTextBox();
		filterTypeDropDownButton = new ToolStripDropDownButton();
		fileSummaryStatusStrip = new StatusStrip();
		selectedFilesStatusLabel = new ToolStripStatusLabel();
		fileSummaryStatusSeparator = new ToolStripSeparator();
		totalFilesStatusLabel = new ToolStripStatusLabel();
		mainMenuStrip.SuspendLayout();
		mainToolStrip.SuspendLayout();
		coverContextMenu.SuspendLayout();
		fileListHeaderContextMenu.SuspendLayout();
		fileListItemContextMenu.SuspendLayout();
		notifyContextMenu.SuspendLayout();
		((ISupportInitialize)mainSplitContainer).BeginInit();
		mainSplitContainer.Panel1.SuspendLayout();
		mainSplitContainer.Panel2.SuspendLayout();
		mainSplitContainer.SuspendLayout();
		tagEditorPanel.SuspendLayout();
		titleRowPanel.SuspendLayout();
		artistRowPanel.SuspendLayout();
		albumRowPanel.SuspendLayout();
		yearRowPanel.SuspendLayout();
		trackDiscGroupPanel.SuspendLayout();
		trackColumnPanel.SuspendLayout();
		trackRowPanel.SuspendLayout();
		discColumnPanel.SuspendLayout();
		discRowPanel.SuspendLayout();
		genreRowPanel.SuspendLayout();
		albumArtistRowPanel.SuspendLayout();
		composerRowPanel.SuspendLayout();
		lyricistRowPanel.SuspendLayout();
		commentRowPanel.SuspendLayout();
		lyricsRowPanel.SuspendLayout();
		coverPanel.SuspendLayout();
		((ISupportInitialize)coverPictureBox).BeginInit();
		statusLabelsPanel.SuspendLayout();
		coverNavigationPanel.SuspendLayout();
		fileFilterStatusStrip.SuspendLayout();
		fileSummaryStatusStrip.SuspendLayout();
		SuspendLayout();
		mainMenuStrip.Items.AddRange(new ToolStripItem[8] { fileMenuItem, editMenuItem, viewMenuItem, tagSourcesMenuItem, batchMenuItem, toolsMenuItem, languageMenuItem, helpMenuItem });
		mainMenuStrip.Location = new Point(0, 0);
		mainMenuStrip.Name = "menuStrip1";
		mainMenuStrip.Padding = new Padding(7, 2, 0, 2);
		mainMenuStrip.Size = new Size(1589, 25);
		mainMenuStrip.TabIndex = 1;
		mainMenuStrip.Text = "menuStrip1";
		fileMenuItem.DropDownItems.AddRange(new ToolStripItem[12]
		{
		changeDirectoryMenuItem, addDirectoryMenuItem, manageDirectoriesMenuItem, fileMenuTagActionsSeparator, saveTagsMenuItem, removeTagsMenuItem, readTagsMenuItem, characterSetMenuItem, chineseConversionMenuItem, tagHistoryMenuItem,
		fileMenuExitSeparator, exitMenuItem
		});
		fileMenuItem.Name = "fileToolStripMenuItem";
		fileMenuItem.ShortcutKeyDisplayString = "";
		fileMenuItem.Size = new Size(39, 21);
		fileMenuItem.Text = "&File";
		changeDirectoryMenuItem.Image = Resources.chgDirToolStripMenuItem_Image;
		changeDirectoryMenuItem.Name = "chgDirToolStripMenuItem";
		changeDirectoryMenuItem.ShortcutKeys = Keys.D | Keys.Control;
		changeDirectoryMenuItem.Size = new Size(222, 22);
		changeDirectoryMenuItem.Text = "Change &directory";
		changeDirectoryMenuItem.Click += ChangeDirectoryButton_Click;
		addDirectoryMenuItem.Image = Resources.addDirsToolStripMenuItem_Image;
		addDirectoryMenuItem.ImageTransparentColor = Color.Magenta;
		addDirectoryMenuItem.Name = "addDirsToolStripMenuItem";
		addDirectoryMenuItem.Size = new Size(222, 22);
		addDirectoryMenuItem.Text = "&Add directory";
		addDirectoryMenuItem.Click += AddFolderButton_Click;
		manageDirectoriesMenuItem.Image = Resources.manageDirsToolStripMenuItem_Image;
		manageDirectoriesMenuItem.Name = "manageDirsToolStripMenuItem";
		manageDirectoriesMenuItem.Size = new Size(222, 22);
		manageDirectoriesMenuItem.Text = "&Manage directorys";
		manageDirectoriesMenuItem.Click += ManageDirectoriesButton_Click;
		fileMenuTagActionsSeparator.Name = "toolStripSeparator";
		fileMenuTagActionsSeparator.Size = new Size(219, 6);
		saveTagsMenuItem.Enabled = false;
		saveTagsMenuItem.Image = Resources.saveToolStripMenuItem_Image;
		saveTagsMenuItem.ImageTransparentColor = Color.Magenta;
		saveTagsMenuItem.Name = "saveToolStripMenuItem";
		saveTagsMenuItem.ShortcutKeys = Keys.S | Keys.Control;
		saveTagsMenuItem.Size = new Size(222, 22);
		saveTagsMenuItem.Text = "&Save tags";
		saveTagsMenuItem.Click += SaveTags_Click;
		removeTagsMenuItem.Enabled = false;
		removeTagsMenuItem.Image = Resources.removeTagToolStripMenuItem_Image;
		removeTagsMenuItem.Name = "removeTagToolStripMenuItem";
		removeTagsMenuItem.ShortcutKeys = Keys.R | Keys.Control;
		removeTagsMenuItem.Size = new Size(222, 22);
		removeTagsMenuItem.Text = "&Remove tags";
		removeTagsMenuItem.Click += ClearTags_Click;
		readTagsMenuItem.Enabled = false;
		readTagsMenuItem.Image = Resources.readTagsToolStripMenuItem_Image;
		readTagsMenuItem.Name = "readTagsToolStripMenuItem";
		readTagsMenuItem.ShortcutKeys = Keys.T | Keys.Control;
		readTagsMenuItem.Size = new Size(222, 22);
		readTagsMenuItem.Text = "Read &tags";
		readTagsMenuItem.Click += RefreshSelectedFiles_Click;
		characterSetMenuItem.Enabled = false;
		characterSetMenuItem.Image = Resources.characterSetToolStripMenuItem_Image;
		characterSetMenuItem.Name = "characterSetToolStripMenuItem";
		characterSetMenuItem.Size = new Size(222, 22);
		characterSetMenuItem.Text = "&Character Set";
		characterSetMenuItem.Click += EditAllTagFieldEncodings_Click;
		chineseConversionMenuItem.DropDownItems.AddRange(new ToolStripItem[2] { convertTagsTraditionalToSimplifiedMenuItem, convertTagsSimplifiedToTraditionalMenuItem });
		chineseConversionMenuItem.Enabled = false;
		chineseConversionMenuItem.Image = Resources.chschtToolStripMenuItem_Image;
		chineseConversionMenuItem.Name = "chschtToolStripMenuItem";
		chineseConversionMenuItem.Size = new Size(222, 22);
		chineseConversionMenuItem.Text = "CHS and CHT c&onversion";
		convertTagsTraditionalToSimplifiedMenuItem.Name = "chtToChsToolStripMenuItem1";
		convertTagsTraditionalToSimplifiedMenuItem.Size = new Size(144, 22);
		convertTagsTraditionalToSimplifiedMenuItem.Text = "CHT to CHS";
		convertTagsTraditionalToSimplifiedMenuItem.Click += ConvertTagsTraditionalToSimplified_Click;
		convertTagsSimplifiedToTraditionalMenuItem.Name = "chsToChtToolStripMenuItem1";
		convertTagsSimplifiedToTraditionalMenuItem.Size = new Size(144, 22);
		convertTagsSimplifiedToTraditionalMenuItem.Text = "CHS to CHT";
		convertTagsSimplifiedToTraditionalMenuItem.Click += ConvertTagsSimplifiedToTraditional_Click;
		tagHistoryMenuItem.Enabled = false;
		tagHistoryMenuItem.Image = Resources.tagsHistoryToolStripMenuItem_Image;
		tagHistoryMenuItem.Name = "tagsHistoryToolStripMenuItem";
		tagHistoryMenuItem.Size = new Size(222, 22);
		tagHistoryMenuItem.Text = "Tags &History";
		tagHistoryMenuItem.Click += RestoreTagsFromHistory_Click;
		fileMenuExitSeparator.Name = "toolStripSeparator1";
		fileMenuExitSeparator.Size = new Size(219, 6);
		exitMenuItem.Image = Resources.exitToolStripMenuItem_Image;
		exitMenuItem.Name = "exitToolStripMenuItem";
		exitMenuItem.Size = new Size(222, 22);
		exitMenuItem.Text = "&Exit";
		exitMenuItem.Click += ExitApplication_Click;
		editMenuItem.DropDownItems.AddRange(new ToolStripItem[9] { selectAllFilesMenuItem, unselectAllFilesMenuItem, invertFileSelectionMenuItem, editSelectionSeparator, undoMenuItem, renameFileMenuItem, removeItemsMenuItem, removeFilesMenuItem, openDirectoryMenuItem });
		editMenuItem.Name = "editToolStripMenuItem";
		editMenuItem.Size = new Size(42, 21);
		editMenuItem.Text = "&Edit";
		selectAllFilesMenuItem.Image = Resources.selallfilesToolStripMenuItem_Image;
		selectAllFilesMenuItem.Name = "selallfilesToolStripMenuItem";
		selectAllFilesMenuItem.ShortcutKeys = Keys.A | Keys.Control;
		selectAllFilesMenuItem.Size = new Size(243, 22);
		selectAllFilesMenuItem.Text = "Select all";
		selectAllFilesMenuItem.Click += SelectAllFiles_Click;
		unselectAllFilesMenuItem.Image = Resources.unselectAllToolStripMenuItem_Image;
		unselectAllFilesMenuItem.Name = "unselectAllToolStripMenuItem";
		unselectAllFilesMenuItem.ShortcutKeys = Keys.U | Keys.Control;
		unselectAllFilesMenuItem.Size = new Size(243, 22);
		unselectAllFilesMenuItem.Text = "&Unselect all";
		unselectAllFilesMenuItem.Click += UnselectAllFiles_Click;
		invertFileSelectionMenuItem.Name = "invertSelectToolStripMenuItem";
		invertFileSelectionMenuItem.ShortcutKeys = Keys.A | Keys.Shift | Keys.Control;
		invertFileSelectionMenuItem.Size = new Size(243, 22);
		invertFileSelectionMenuItem.Text = "&Invert selection";
		invertFileSelectionMenuItem.Click += InvertFileSelection_Click;
		editSelectionSeparator.Name = "toolStripSeparator2";
		editSelectionSeparator.Size = new Size(240, 6);
		undoMenuItem.Enabled = false;
		undoMenuItem.Image = Resources.undoToolStripMenuItem_Image;
		undoMenuItem.Name = "undoToolStripMenuItem";
		undoMenuItem.Size = new Size(243, 22);
		undoMenuItem.Text = "Undo";
		undoMenuItem.Click += UndoLastOperation_Click;
		renameFileMenuItem.Enabled = false;
		renameFileMenuItem.Name = "renameFileToolStripMenuItem";
		renameFileMenuItem.Size = new Size(243, 22);
		renameFileMenuItem.Text = "Rename";
		renameFileMenuItem.Click += BeginRenameSelectedFile_Click;
		removeItemsMenuItem.Enabled = false;
		removeItemsMenuItem.Name = "removeItemToolStripMenuItem";
		removeItemsMenuItem.ShortcutKeys = Keys.Delete;
		removeItemsMenuItem.Size = new Size(243, 22);
		removeItemsMenuItem.Text = "&Remove items";
		removeItemsMenuItem.Click += RemoveSelectedItemsFromList_Click;
		removeFilesMenuItem.Enabled = false;
		removeFilesMenuItem.Name = "removeFileToolStripMenuItem";
		removeFilesMenuItem.Size = new Size(243, 22);
		removeFilesMenuItem.Text = "Remove &files";
		removeFilesMenuItem.Click += DeleteSelectedFiles_Click;
		openDirectoryMenuItem.Enabled = false;
		openDirectoryMenuItem.Name = "openDirectoryToolStripMenuItem";
		openDirectoryMenuItem.Size = new Size(243, 22);
		openDirectoryMenuItem.Text = "&Open directory";
		openDirectoryMenuItem.Click += RevealSelectedFileInExplorer_Click;
		viewMenuItem.DropDownItems.AddRange(new ToolStripItem[2] { refreshMenuItem, customizeColumnsMenuItem });
		viewMenuItem.Name = "viewToolStripMenuItem";
		viewMenuItem.Size = new Size(47, 21);
		viewMenuItem.Text = "&View";
		refreshMenuItem.Image = Resources.refreshToolStripMenuItem_Image;
		refreshMenuItem.Name = "refreshToolStripMenuItem";
		refreshMenuItem.ShortcutKeys = Keys.F5;
		refreshMenuItem.Size = new Size(188, 22);
		refreshMenuItem.Text = "&Refresh";
		refreshMenuItem.Click += RefreshConfiguredFileList_Click;
		customizeColumnsMenuItem.Name = "customColToolStripMenuItem";
		customizeColumnsMenuItem.Size = new Size(188, 22);
		customizeColumnsMenuItem.Text = "&Customize columns";
		customizeColumnsMenuItem.Click += ConfigureFileListColumns_Click;
		tagSourcesMenuItem.DropDownItems.AddRange(new ToolStripItem[3] { coverSourceMenuItem, lyricSourceMenuItem, combinedTagSourceMenuItem });
		tagSourcesMenuItem.Enabled = false;
		tagSourcesMenuItem.Name = "tagSrcToolStripMenuItem";
		tagSourcesMenuItem.Size = new Size(92, 21);
		tagSourcesMenuItem.Text = "Tag &Sources";
		coverSourceMenuItem.DropDownItems.AddRange(new ToolStripItem[1] { defaultCoverSourceMenuItem });
		coverSourceMenuItem.Image = Resources.picSrcToolStripMenuItem_Image;
		coverSourceMenuItem.Name = "picSrcToolStripMenuItem";
		coverSourceMenuItem.Size = new Size(150, 22);
		coverSourceMenuItem.Text = "&Picture";
		defaultCoverSourceMenuItem.Name = "defaultPicSrcToolStripMenuItem";
		defaultCoverSourceMenuItem.Size = new Size(117, 22);
		defaultCoverSourceMenuItem.Text = "Default";
		defaultCoverSourceMenuItem.Click += CoverSourceMenuItem_Click;
		lyricSourceMenuItem.DropDownItems.AddRange(new ToolStripItem[1] { defaultLyricSourceMenuItem });
		lyricSourceMenuItem.Image = Resources.lyricSrcToolStripMenuItem_Image;
		lyricSourceMenuItem.Name = "lyricSrcToolStripMenuItem";
		lyricSourceMenuItem.Size = new Size(150, 22);
		lyricSourceMenuItem.Text = "&Lyric";
		defaultLyricSourceMenuItem.Name = "defaultLyricSrcToolStripMenuItem";
		defaultLyricSourceMenuItem.Size = new Size(117, 22);
		defaultLyricSourceMenuItem.Text = "Default";
		defaultLyricSourceMenuItem.Click += LyricSourceMenuItem_Click;
		combinedTagSourceMenuItem.DropDownItems.AddRange(new ToolStripItem[1] { defaultCombinedTagSourceMenuItem });
		combinedTagSourceMenuItem.Image = Resources.combTagsSrcToolStripMenuItem_Image;
		combinedTagSourceMenuItem.Name = "combTagsSrcToolStripMenuItem";
		combinedTagSourceMenuItem.Size = new Size(150, 22);
		combinedTagSourceMenuItem.Text = "&Combination";
		defaultCombinedTagSourceMenuItem.Name = "defaultCombTagsSrcToolStripMenuItem";
		defaultCombinedTagSourceMenuItem.Size = new Size(117, 22);
		defaultCombinedTagSourceMenuItem.Text = "Default";
		defaultCombinedTagSourceMenuItem.Click += TagSourceMenuItem_Click;
		batchMenuItem.DropDownItems.AddRange(new ToolStripItem[5] { batchAutoMatchTagsMenuItem, batchLyricMenuItem, batchExtractCoverMenuItem, batchFilenameRelatedMenuItem, batchChineseConversionMenuItem });
		batchMenuItem.Enabled = false;
		batchMenuItem.Name = "batchToolStripMenuItem";
		batchMenuItem.Size = new Size(52, 21);
		batchMenuItem.Text = "&Batch";
		batchAutoMatchTagsMenuItem.Image = Resources.batchAutoMatchTagsToolStripButton_Image;
		batchAutoMatchTagsMenuItem.Name = "batchAutoMatchTagsToolStripMenuItem";
		batchAutoMatchTagsMenuItem.Size = new Size(221, 22);
		batchAutoMatchTagsMenuItem.Text = "&Auto match tags";
		batchAutoMatchTagsMenuItem.Click += BatchAutoMatchTags_Click;
		batchLyricMenuItem.DropDownItems.AddRange(new ToolStripItem[6] { reformatLyricTimeTagsMenuItem, removeLyricTimeTagsMenuItem, deleteBlankLyricLinesMenuItem, deleteLyricHeaderTagsMenuItem, saveLyricsMenuItem, importLrcFilesMenuItem });
		batchLyricMenuItem.Name = "batchLyricToolStripMenuItem";
		batchLyricMenuItem.Size = new Size(221, 22);
		batchLyricMenuItem.Text = "&Lyric";
		reformatLyricTimeTagsMenuItem.Name = "batchReformatTimetagToolStripMenuItem";
		reformatLyricTimeTagsMenuItem.Size = new Size(220, 22);
		reformatLyricTimeTagsMenuItem.Text = "Reformat timetag";
		reformatLyricTimeTagsMenuItem.Click += ReformatLyricTimeTags_Click;
		removeLyricTimeTagsMenuItem.Name = "batchRemoveTimetagToolStripMenuItem";
		removeLyricTimeTagsMenuItem.Size = new Size(220, 22);
		removeLyricTimeTagsMenuItem.Text = "Remove timetag";
		removeLyricTimeTagsMenuItem.Click += RemoveLyricTimeTags_Click;
		deleteBlankLyricLinesMenuItem.Name = "batchDeleteLinesOfBlankTextToolStripMenuItem";
		deleteBlankLyricLinesMenuItem.Size = new Size(220, 22);
		deleteBlankLyricLinesMenuItem.Text = "Delete lines of blank text";
		deleteBlankLyricLinesMenuItem.Click += DeleteBlankLyricLines_Click;
		deleteLyricHeaderTagsMenuItem.Name = "batchDeleteHeadTagsToolStripMenuItem";
		deleteLyricHeaderTagsMenuItem.Size = new Size(220, 22);
		deleteLyricHeaderTagsMenuItem.Text = "Delete head tags";
		deleteLyricHeaderTagsMenuItem.Click += DeleteLyricHeaderTags_Click;
		saveLyricsMenuItem.Image = Resources.batchSaveAsLrcFileToolStripSplitButton_Image;
		saveLyricsMenuItem.Name = "batchSaveAsLrcFileToolStripMenuItem";
		saveLyricsMenuItem.Size = new Size(220, 22);
		saveLyricsMenuItem.Text = "Save as Lrc file";
		saveLyricsMenuItem.Click += SaveLyrics_Click;
		importLrcFilesMenuItem.Name = "batchImportLrcFileToolStripMenuItem";
		importLrcFilesMenuItem.Size = new Size(220, 22);
		importLrcFilesMenuItem.Text = "Import Lrc file";
		importLrcFilesMenuItem.Click += ImportLrcFiles_Click;
		batchExtractCoverMenuItem.Image = Resources.batchExtractCoverToolStripButton_Image;
		batchExtractCoverMenuItem.Name = "batchExtractCoverToolStripMenuItem";
		batchExtractCoverMenuItem.Size = new Size(221, 22);
		batchExtractCoverMenuItem.Text = "&Extract cover";
		batchExtractCoverMenuItem.Click += ExtractCovers_Click;
		batchFilenameRelatedMenuItem.Image = Resources.batchFilenameRelToolStripButton_Image;
		batchFilenameRelatedMenuItem.Name = "batchFilenameRelToolStripMenuItem";
		batchFilenameRelatedMenuItem.Size = new Size(221, 22);
		batchFilenameRelatedMenuItem.Text = "&File name-related";
		batchFilenameRelatedMenuItem.Click += BatchFilenameOrTagsFromPattern_Click;
		batchChineseConversionMenuItem.DropDownItems.AddRange(new ToolStripItem[4] { batchTagsTraditionalToSimplifiedMenuItem, batchTagsSimplifiedToTraditionalMenuItem, batchFilenameTraditionalToSimplifiedMenuItem, batchFilenameSimplifiedToTraditionalMenuItem });
		batchChineseConversionMenuItem.Image = Resources.chschtToolStripMenuItem_Image;
		batchChineseConversionMenuItem.Name = "batchChschtToolStripMenuItem";
		batchChineseConversionMenuItem.Size = new Size(221, 22);
		batchChineseConversionMenuItem.Text = "CHS and CHT c&onversion";
		batchTagsTraditionalToSimplifiedMenuItem.Name = "batchTagsChtToChsToolStripMenuItem";
		batchTagsTraditionalToSimplifiedMenuItem.Size = new Size(249, 22);
		batchTagsTraditionalToSimplifiedMenuItem.Text = "Convert tags: CHT to CHS";
		batchTagsTraditionalToSimplifiedMenuItem.Click += ConvertSelectedTagsTraditionalToSimplified_Click;
		batchTagsSimplifiedToTraditionalMenuItem.Name = "batchTagsChsToChtToolStripMenuItem";
		batchTagsSimplifiedToTraditionalMenuItem.Size = new Size(249, 22);
		batchTagsSimplifiedToTraditionalMenuItem.Text = "Convert tags: CHS to CHT";
		batchTagsSimplifiedToTraditionalMenuItem.Click += ConvertSelectedTagsSimplifiedToTraditional_Click;
		batchFilenameTraditionalToSimplifiedMenuItem.Name = "batchFilenameChtToChsToolStripMenuItem";
		batchFilenameTraditionalToSimplifiedMenuItem.Size = new Size(249, 22);
		batchFilenameTraditionalToSimplifiedMenuItem.Text = "Convert filename: CHT to CHS";
		batchFilenameTraditionalToSimplifiedMenuItem.Click += ConvertSelectedFilenamesTraditionalToSimplified_Click;
		batchFilenameSimplifiedToTraditionalMenuItem.Name = "batchFilenameChsToChtToolStripMenuItem";
		batchFilenameSimplifiedToTraditionalMenuItem.Size = new Size(249, 22);
		batchFilenameSimplifiedToTraditionalMenuItem.Text = "Convert filename: CHS to CHT";
		batchFilenameSimplifiedToTraditionalMenuItem.Click += ConvertSelectedFilenamesSimplifiedToTraditional_Click;
		toolsMenuItem.DropDownItems.AddRange(new ToolStripItem[1] { optionsMenuItem });
		toolsMenuItem.Name = "toolsToolStripMenuItem";
		toolsMenuItem.Size = new Size(52, 21);
		toolsMenuItem.Text = "&Tools";
		optionsMenuItem.Image = Resources.optionsToolStripMenuItem_Image;
		optionsMenuItem.Name = "optionsToolStripMenuItem";
		optionsMenuItem.ShortcutKeys = Keys.O | Keys.Control;
		optionsMenuItem.Size = new Size(169, 22);
		optionsMenuItem.Text = "&Options";
		optionsMenuItem.Click += OpenOptions_Click;
		languageMenuItem.DropDownItems.AddRange(new ToolStripItem[3] { englishLanguageMenuItem, simplifiedChineseLanguageMenuItem, traditionalChineseLanguageMenuItem });
		languageMenuItem.Name = "languageToolStripMenuItem";
		languageMenuItem.Size = new Size(77, 21);
		languageMenuItem.Text = "&Language";
		englishLanguageMenuItem.Name = "langenglishToolStripMenuItem";
		englishLanguageMenuItem.Size = new Size(187, 22);
		englishLanguageMenuItem.Text = "&English";
		englishLanguageMenuItem.Click += SetLanguageEnglish_Click;
		simplifiedChineseLanguageMenuItem.Name = "langchsToolStripMenuItem";
		simplifiedChineseLanguageMenuItem.Size = new Size(187, 22);
		simplifiedChineseLanguageMenuItem.Text = "&Simplified Chinese";
		simplifiedChineseLanguageMenuItem.Click += SetLanguageSimplifiedChinese_Click;
		traditionalChineseLanguageMenuItem.Name = "langchtToolStripMenuItem";
		traditionalChineseLanguageMenuItem.Size = new Size(187, 22);
		traditionalChineseLanguageMenuItem.Text = "&Traditional Chinese";
		traditionalChineseLanguageMenuItem.Click += SetLanguageTraditionalChinese_Click;
		helpMenuItem.DropDownItems.AddRange(new ToolStripItem[3] { checkForUpdatesMenuItem, musicTagWebsiteMenuItem, aboutMenuItem });
		helpMenuItem.Name = "helpToolStripMenuItem";
		helpMenuItem.Size = new Size(47, 21);
		helpMenuItem.Text = "&Help";
		checkForUpdatesMenuItem.Name = "checkNewVerToolStripMenuItem";
		checkForUpdatesMenuItem.Size = new Size(205, 22);
		checkForUpdatesMenuItem.Text = "&Check for new version";
		checkForUpdatesMenuItem.Click += CheckForUpdates_Click;
		musicTagWebsiteMenuItem.Name = "musicTagWebsiteToolStripMenuItem";
		musicTagWebsiteMenuItem.Size = new Size(205, 22);
		musicTagWebsiteMenuItem.Text = "Music Tag &Website";
		musicTagWebsiteMenuItem.Click += OpenMusicTagWebsite_Click;
		aboutMenuItem.Name = "aboutToolStripMenuItem";
		aboutMenuItem.Size = new Size(205, 22);
		aboutMenuItem.Text = "&About";
		aboutMenuItem.Click += ShowAboutDialog_Click;
		mainToolStrip.Items.AddRange(new ToolStripItem[28]
		{
		changeDirectoryToolStripButton, addDirectoriesToolStripButton, manageDirectoriesToolStripButton, directoryToolbarSeparator, saveTagsToolStripButton, removeTagsToolStripButton, undoToolStripButton, readTagsToolStripButton, characterSetToolStripButton, chineseConversionToolStripDropDownButton,
		tagHistoryToolStripButton, tagActionsToolbarSeparator, selectAllFilesToolStripButton, unselectAllFilesToolStripButton, selectionToolbarSeparator, refreshToolStripButton, sourceToolbarSeparator, coverSourceToolStripSplitButton, lyricSourceToolStripSplitButton, combinedTagSourceToolStripSplitButton,
		batchToolbarStartSeparator, batchAutoMatchTagsToolStripButton, batchSaveAsLrcToolStripSplitButton, batchExtractCoverToolStripButton, batchChineseConversionToolStripDropDownButton, batchFilenameRelatedToolStripButton, batchToolbarOptionsSeparator, optionsToolStripButton
		});
		mainToolStrip.Location = new Point(0, 25);
		mainToolStrip.Name = "toolStrip1";
		mainToolStrip.Size = new Size(1589, 25);
		mainToolStrip.TabIndex = 2;
		mainToolStrip.Text = "toolStrip1";
		changeDirectoryToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		changeDirectoryToolStripButton.Image = Resources.chgDirToolStripMenuItem_Image;
		changeDirectoryToolStripButton.ImageTransparentColor = Color.Magenta;
		changeDirectoryToolStripButton.Name = "chgDirToolStripButton";
		changeDirectoryToolStripButton.Size = new Size(23, 22);
		changeDirectoryToolStripButton.Text = "Change &directory";
		changeDirectoryToolStripButton.Click += ChangeDirectoryButton_Click;
		addDirectoriesToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		addDirectoriesToolStripButton.Image = Resources.addDirsToolStripMenuItem_Image;
		addDirectoriesToolStripButton.ImageTransparentColor = Color.Magenta;
		addDirectoriesToolStripButton.Name = "addDirsToolStripButton";
		addDirectoriesToolStripButton.Size = new Size(23, 22);
		addDirectoriesToolStripButton.Text = "add &Directories";
		addDirectoriesToolStripButton.Click += AddFolderButton_Click;
		manageDirectoriesToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		manageDirectoriesToolStripButton.Image = Resources.manageDirsToolStripMenuItem_Image;
		manageDirectoriesToolStripButton.ImageTransparentColor = Color.Magenta;
		manageDirectoriesToolStripButton.Name = "manageDirsToolStripButton";
		manageDirectoriesToolStripButton.Size = new Size(23, 22);
		manageDirectoriesToolStripButton.Text = "&Manage directorys";
		manageDirectoriesToolStripButton.Click += ManageDirectoriesButton_Click;
		directoryToolbarSeparator.Name = "toolStripSeparator8";
		directoryToolbarSeparator.Size = new Size(6, 25);
		saveTagsToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		saveTagsToolStripButton.Enabled = false;
		saveTagsToolStripButton.Image = Resources.saveToolStripMenuItem_Image;
		saveTagsToolStripButton.ImageTransparentColor = Color.Magenta;
		saveTagsToolStripButton.Name = "saveToolStripButton";
		saveTagsToolStripButton.Size = new Size(23, 22);
		saveTagsToolStripButton.Text = "Save(&S)";
		saveTagsToolStripButton.Click += SaveTags_Click;
		removeTagsToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		removeTagsToolStripButton.Enabled = false;
		removeTagsToolStripButton.Image = Resources.removeTagToolStripMenuItem_Image;
		removeTagsToolStripButton.ImageTransparentColor = Color.Magenta;
		removeTagsToolStripButton.Name = "removeTagToolStripButton";
		removeTagsToolStripButton.Size = new Size(23, 22);
		removeTagsToolStripButton.Text = "&Remove tags";
		removeTagsToolStripButton.Click += ClearTags_Click;
		undoToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		undoToolStripButton.Enabled = false;
		undoToolStripButton.Image = Resources.undoToolStripMenuItem_Image;
		undoToolStripButton.ImageTransparentColor = Color.Magenta;
		undoToolStripButton.Name = "undoToolStripButton";
		undoToolStripButton.Size = new Size(23, 22);
		undoToolStripButton.Text = "&Undo";
		undoToolStripButton.Click += UndoLastOperation_Click;
		readTagsToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		readTagsToolStripButton.Enabled = false;
		readTagsToolStripButton.Image = Resources.readTagsToolStripMenuItem_Image;
		readTagsToolStripButton.ImageTransparentColor = Color.Magenta;
		readTagsToolStripButton.Name = "readTagsToolStripButton";
		readTagsToolStripButton.Size = new Size(23, 22);
		readTagsToolStripButton.Text = "Read &tags";
		readTagsToolStripButton.Click += RefreshSelectedFiles_Click;
		characterSetToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		characterSetToolStripButton.Enabled = false;
		characterSetToolStripButton.Image = Resources.characterSetToolStripMenuItem_Image;
		characterSetToolStripButton.ImageTransparentColor = Color.Magenta;
		characterSetToolStripButton.Name = "characterSetToolStripButton";
		characterSetToolStripButton.Size = new Size(23, 22);
		characterSetToolStripButton.Text = "&Character Set";
		characterSetToolStripButton.Click += EditAllTagFieldEncodings_Click;
		chineseConversionToolStripDropDownButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		chineseConversionToolStripDropDownButton.DropDownItems.AddRange(new ToolStripItem[2] { convertTagsTraditionalToSimplifiedToolStripMenuItem, convertTagsSimplifiedToTraditionalToolStripMenuItem });
		chineseConversionToolStripDropDownButton.Enabled = false;
		chineseConversionToolStripDropDownButton.Image = Resources.chschtToolStripMenuItem_Image;
		chineseConversionToolStripDropDownButton.ImageTransparentColor = Color.Magenta;
		chineseConversionToolStripDropDownButton.Name = "chschtToolStripButton";
		chineseConversionToolStripDropDownButton.Size = new Size(29, 22);
		chineseConversionToolStripDropDownButton.Text = "toolStripDropDownButton1";
		convertTagsTraditionalToSimplifiedToolStripMenuItem.Name = "chtToChsToolStripMenuItem";
		convertTagsTraditionalToSimplifiedToolStripMenuItem.Size = new Size(144, 22);
		convertTagsTraditionalToSimplifiedToolStripMenuItem.Text = "CHT to CHS";
		convertTagsTraditionalToSimplifiedToolStripMenuItem.Click += ConvertTagsTraditionalToSimplified_Click;
		convertTagsSimplifiedToTraditionalToolStripMenuItem.Name = "chsToChtToolStripMenuItem";
		convertTagsSimplifiedToTraditionalToolStripMenuItem.Size = new Size(144, 22);
		convertTagsSimplifiedToTraditionalToolStripMenuItem.Text = "CHS to CHT";
		convertTagsSimplifiedToTraditionalToolStripMenuItem.Click += ConvertTagsSimplifiedToTraditional_Click;
		tagHistoryToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		tagHistoryToolStripButton.Enabled = false;
		tagHistoryToolStripButton.Image = Resources.tagsHistoryToolStripMenuItem_Image;
		tagHistoryToolStripButton.ImageTransparentColor = Color.Magenta;
		tagHistoryToolStripButton.Name = "tagsHistoryToolStripButton";
		tagHistoryToolStripButton.Size = new Size(23, 22);
		tagHistoryToolStripButton.Text = "Tags &History";
		tagHistoryToolStripButton.Click += RestoreTagsFromHistory_Click;
		tagActionsToolbarSeparator.Name = "toolStripSeparator6";
		tagActionsToolbarSeparator.Size = new Size(6, 25);
		selectAllFilesToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		selectAllFilesToolStripButton.Image = Resources.selallfilesToolStripMenuItem_Image;
		selectAllFilesToolStripButton.ImageTransparentColor = Color.Magenta;
		selectAllFilesToolStripButton.Name = "selallfilesToolStripButton";
		selectAllFilesToolStripButton.Size = new Size(23, 22);
		selectAllFilesToolStripButton.Text = "Select all &files";
		selectAllFilesToolStripButton.Click += SelectAllFiles_Click;
		unselectAllFilesToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		unselectAllFilesToolStripButton.Image = Resources.unselectAllToolStripMenuItem_Image;
		unselectAllFilesToolStripButton.ImageTransparentColor = Color.Magenta;
		unselectAllFilesToolStripButton.Name = "unselectAllToolStripButton";
		unselectAllFilesToolStripButton.Size = new Size(23, 22);
		unselectAllFilesToolStripButton.Text = "&Unselect all";
		unselectAllFilesToolStripButton.Click += UnselectAllFiles_Click;
		selectionToolbarSeparator.Name = "toolStripSeparator3";
		selectionToolbarSeparator.Size = new Size(6, 25);
		refreshToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		refreshToolStripButton.Image = Resources.refreshToolStripMenuItem_Image;
		refreshToolStripButton.ImageTransparentColor = Color.Magenta;
		refreshToolStripButton.Name = "refreshToolStripButton";
		refreshToolStripButton.Size = new Size(23, 22);
		refreshToolStripButton.Text = "&Refresh";
		refreshToolStripButton.Click += RefreshConfiguredFileList_Click;
		sourceToolbarSeparator.Name = "toolStripSeparator5";
		sourceToolbarSeparator.Size = new Size(6, 25);
		coverSourceToolStripSplitButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		coverSourceToolStripSplitButton.Enabled = false;
		coverSourceToolStripSplitButton.Image = Resources.picSrcToolStripMenuItem_Image;
		coverSourceToolStripSplitButton.ImageTransparentColor = Color.Magenta;
		coverSourceToolStripSplitButton.Name = "picSrcToolStripSplitButton";
		coverSourceToolStripSplitButton.Size = new Size(32, 22);
		coverSourceToolStripSplitButton.Text = "&Picture Sources";
		coverSourceToolStripSplitButton.ButtonClick += CoverSourceMenuItem_Click;
		lyricSourceToolStripSplitButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		lyricSourceToolStripSplitButton.Enabled = false;
		lyricSourceToolStripSplitButton.Image = Resources.lyricSrcToolStripMenuItem_Image;
		lyricSourceToolStripSplitButton.ImageTransparentColor = Color.Magenta;
		lyricSourceToolStripSplitButton.Name = "lyricSrcToolStripSplitButton";
		lyricSourceToolStripSplitButton.Size = new Size(32, 22);
		lyricSourceToolStripSplitButton.Text = "&Lyric Sources";
		lyricSourceToolStripSplitButton.ButtonClick += LyricSourceMenuItem_Click;
		combinedTagSourceToolStripSplitButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		combinedTagSourceToolStripSplitButton.Enabled = false;
		combinedTagSourceToolStripSplitButton.Image = Resources.combTagsSrcToolStripMenuItem_Image;
		combinedTagSourceToolStripSplitButton.ImageTransparentColor = Color.Magenta;
		combinedTagSourceToolStripSplitButton.Name = "combTagsSrcToolStripSplitButton";
		combinedTagSourceToolStripSplitButton.Size = new Size(32, 22);
		combinedTagSourceToolStripSplitButton.Text = "Combination tags";
		combinedTagSourceToolStripSplitButton.ButtonClick += TagSourceMenuItem_Click;
		batchToolbarStartSeparator.Name = "toolStripSeparator10";
		batchToolbarStartSeparator.Size = new Size(6, 25);
		batchAutoMatchTagsToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		batchAutoMatchTagsToolStripButton.Enabled = false;
		batchAutoMatchTagsToolStripButton.Image = Resources.batchAutoMatchTagsToolStripButton_Image;
		batchAutoMatchTagsToolStripButton.ImageTransparentColor = Color.Magenta;
		batchAutoMatchTagsToolStripButton.Name = "batchAutoMatchTagsToolStripButton";
		batchAutoMatchTagsToolStripButton.Size = new Size(23, 22);
		batchAutoMatchTagsToolStripButton.Text = "&Auto match tags";
		batchAutoMatchTagsToolStripButton.Click += BatchAutoMatchTags_Click;
		batchSaveAsLrcToolStripSplitButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		batchSaveAsLrcToolStripSplitButton.DropDownItems.AddRange(new ToolStripItem[5] { reformatLyricTimeTagsToolStripMenuItem, removeLyricTimeTagsToolStripMenuItem, deleteBlankLyricLinesToolStripMenuItem, deleteLyricHeaderTagsToolStripMenuItem, importLrcFilesToolStripMenuItem });
		batchSaveAsLrcToolStripSplitButton.Enabled = false;
		batchSaveAsLrcToolStripSplitButton.Image = Resources.batchSaveAsLrcFileToolStripSplitButton_Image;
		batchSaveAsLrcToolStripSplitButton.ImageTransparentColor = Color.Magenta;
		batchSaveAsLrcToolStripSplitButton.Name = "batchSaveAsLrcFileToolStripSplitButton";
		batchSaveAsLrcToolStripSplitButton.Size = new Size(32, 22);
		batchSaveAsLrcToolStripSplitButton.Text = "Save as Lrc file";
		batchSaveAsLrcToolStripSplitButton.ButtonClick += SaveLyrics_Click;
		reformatLyricTimeTagsToolStripMenuItem.Name = "batchReformatTimetagToolStripMenuItem1";
		reformatLyricTimeTagsToolStripMenuItem.Size = new Size(220, 22);
		reformatLyricTimeTagsToolStripMenuItem.Text = "Reformat timetag";
		reformatLyricTimeTagsToolStripMenuItem.Click += ReformatLyricTimeTags_Click;
		removeLyricTimeTagsToolStripMenuItem.Name = "batchRemoveTimetagToolStripMenuItem1";
		removeLyricTimeTagsToolStripMenuItem.Size = new Size(220, 22);
		removeLyricTimeTagsToolStripMenuItem.Text = "Remove timetag";
		removeLyricTimeTagsToolStripMenuItem.Click += RemoveLyricTimeTags_Click;
		deleteBlankLyricLinesToolStripMenuItem.Name = "batchDeleteLinesOfBlankTextToolStripMenuItem1";
		deleteBlankLyricLinesToolStripMenuItem.Size = new Size(220, 22);
		deleteBlankLyricLinesToolStripMenuItem.Text = "Delete lines of blank text";
		deleteBlankLyricLinesToolStripMenuItem.Click += DeleteBlankLyricLines_Click;
		deleteLyricHeaderTagsToolStripMenuItem.Name = "batchDeleteHeadTagsToolStripMenuItem1";
		deleteLyricHeaderTagsToolStripMenuItem.Size = new Size(220, 22);
		deleteLyricHeaderTagsToolStripMenuItem.Text = "Delete head tags";
		deleteLyricHeaderTagsToolStripMenuItem.Click += DeleteLyricHeaderTags_Click;
		importLrcFilesToolStripMenuItem.Name = "batchImportLrcFileToolStripMenuItem1";
		importLrcFilesToolStripMenuItem.Size = new Size(220, 22);
		importLrcFilesToolStripMenuItem.Text = "Import Lrc file";
		importLrcFilesToolStripMenuItem.Click += ImportLrcFiles_Click;
		batchExtractCoverToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		batchExtractCoverToolStripButton.Enabled = false;
		batchExtractCoverToolStripButton.Image = Resources.batchExtractCoverToolStripButton_Image;
		batchExtractCoverToolStripButton.ImageTransparentColor = Color.Magenta;
		batchExtractCoverToolStripButton.Name = "batchExtractCoverToolStripButton";
		batchExtractCoverToolStripButton.Size = new Size(23, 22);
		batchExtractCoverToolStripButton.Text = "Extract cover";
		batchExtractCoverToolStripButton.Click += ExtractCovers_Click;
		batchChineseConversionToolStripDropDownButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		batchChineseConversionToolStripDropDownButton.DropDownItems.AddRange(new ToolStripItem[4] { batchTagsTraditionalToSimplifiedToolStripMenuItem, batchTagsSimplifiedToTraditionalToolStripMenuItem, batchFilenameTraditionalToSimplifiedToolStripMenuItem, batchFilenameSimplifiedToTraditionalToolStripMenuItem });
		batchChineseConversionToolStripDropDownButton.Enabled = false;
		batchChineseConversionToolStripDropDownButton.Image = Resources.chschtToolStripMenuItem_Image;
		batchChineseConversionToolStripDropDownButton.ImageTransparentColor = Color.Magenta;
		batchChineseConversionToolStripDropDownButton.Name = "batchChschtToolStripButton";
		batchChineseConversionToolStripDropDownButton.Size = new Size(29, 22);
		batchChineseConversionToolStripDropDownButton.Text = "toolStripDropDownButton1";
		batchTagsTraditionalToSimplifiedToolStripMenuItem.Name = "batchTagsChtToChsToolStripMenuItem1";
		batchTagsTraditionalToSimplifiedToolStripMenuItem.Size = new Size(249, 22);
		batchTagsTraditionalToSimplifiedToolStripMenuItem.Text = "Convert tags: CHT to CHS";
		batchTagsTraditionalToSimplifiedToolStripMenuItem.Click += ConvertSelectedTagsTraditionalToSimplified_Click;
		batchTagsSimplifiedToTraditionalToolStripMenuItem.Name = "batchTagsChsToChtToolStripMenuItem1";
		batchTagsSimplifiedToTraditionalToolStripMenuItem.Size = new Size(249, 22);
		batchTagsSimplifiedToTraditionalToolStripMenuItem.Text = "Convert tags: CHS to CHT";
		batchTagsSimplifiedToTraditionalToolStripMenuItem.Click += ConvertSelectedTagsSimplifiedToTraditional_Click;
		batchFilenameTraditionalToSimplifiedToolStripMenuItem.Name = "batchFilenameChtToChsToolStripMenuItem1";
		batchFilenameTraditionalToSimplifiedToolStripMenuItem.Size = new Size(249, 22);
		batchFilenameTraditionalToSimplifiedToolStripMenuItem.Text = "Convert filename: CHT to CHS";
		batchFilenameTraditionalToSimplifiedToolStripMenuItem.Click += ConvertSelectedFilenamesTraditionalToSimplified_Click;
		batchFilenameSimplifiedToTraditionalToolStripMenuItem.Name = "batchFilenameChsToChtToolStripMenuItem1";
		batchFilenameSimplifiedToTraditionalToolStripMenuItem.Size = new Size(249, 22);
		batchFilenameSimplifiedToTraditionalToolStripMenuItem.Text = "Convert filename: CHS to CHT";
		batchFilenameSimplifiedToTraditionalToolStripMenuItem.Click += ConvertSelectedFilenamesSimplifiedToTraditional_Click;
		batchFilenameRelatedToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		batchFilenameRelatedToolStripButton.Enabled = false;
		batchFilenameRelatedToolStripButton.Image = Resources.batchFilenameRelToolStripButton_Image;
		batchFilenameRelatedToolStripButton.ImageTransparentColor = Color.Magenta;
		batchFilenameRelatedToolStripButton.Name = "batchFilenameRelToolStripButton";
		batchFilenameRelatedToolStripButton.Size = new Size(23, 22);
		batchFilenameRelatedToolStripButton.Text = "File name-related";
		batchFilenameRelatedToolStripButton.Click += BatchFilenameOrTagsFromPattern_Click;
		batchToolbarOptionsSeparator.Name = "toolStripSeparator7";
		batchToolbarOptionsSeparator.Size = new Size(6, 25);
		optionsToolStripButton.DisplayStyle = ToolStripItemDisplayStyle.Image;
		optionsToolStripButton.Image = Resources.optionsToolStripMenuItem_Image;
		optionsToolStripButton.ImageTransparentColor = Color.Magenta;
		optionsToolStripButton.Name = "optionsToolStripButton";
		optionsToolStripButton.Size = new Size(23, 22);
		optionsToolStripButton.Text = "&Options";
		optionsToolStripButton.Click += OpenOptions_Click;
		localCoverFileDialog.Filter = componentResourceManager.GetString("openFileDialog1.Filter");
		localCoverFileDialog.Multiselect = true;
		localCoverFileDialog.RestoreDirectory = true;
		coverContextMenu.Items.AddRange(new ToolStripItem[7] { addCoverMenuItem, changeCoverResolutionMenuItem, removeCoverMenuItem, openCoverMenuItem, extractCoverMenuItem, coverContextMenuSeparator, coverTypeMenuItem });
		coverContextMenu.Name = "pictureBoxContextMenuStrip";
		coverContextMenu.Size = new Size(186, 142);
		addCoverMenuItem.DropDownItems.AddRange(new ToolStripItem[3] { chooseLocalCoverMenuItem, searchCoverFromNetworkMenuItem, chooseCoverFromTagsMenuItem });
		addCoverMenuItem.Name = "addCoverToolStripMenuItem";
		addCoverMenuItem.Size = new Size(185, 22);
		addCoverMenuItem.Text = "Add cover";
		chooseLocalCoverMenuItem.Name = "chooseLocalFileToolStripMenuItem";
		chooseLocalCoverMenuItem.Size = new Size(202, 22);
		chooseLocalCoverMenuItem.Text = "Choose Local file";
		chooseLocalCoverMenuItem.Click += ChooseLocalCover_Click;
		searchCoverFromNetworkMenuItem.Name = "searchFromWebToolStripMenuItem";
		searchCoverFromNetworkMenuItem.Size = new Size(202, 22);
		searchCoverFromNetworkMenuItem.Text = "Search from network";
		searchCoverFromNetworkMenuItem.Click += SearchCoverFromNetwork_Click;
		chooseCoverFromTagsMenuItem.Name = "chooseFromFileTagsToolStripMenuItem";
		chooseCoverFromTagsMenuItem.Size = new Size(202, 22);
		chooseCoverFromTagsMenuItem.Text = "Choose from file tags";
		chooseCoverFromTagsMenuItem.Click += ChooseCoverFromFileTags_Click;
		changeCoverResolutionMenuItem.Name = "changeResolutionCoverToolStripMenuItem";
		changeCoverResolutionMenuItem.Size = new Size(185, 22);
		changeCoverResolutionMenuItem.Text = "Change Resolution";
		changeCoverResolutionMenuItem.Click += ToggleCoverResolutionLimit_Click;
		removeCoverMenuItem.Name = "removeCoverToolStripMenuItem";
		removeCoverMenuItem.Size = new Size(185, 22);
		removeCoverMenuItem.Text = "Remove cover";
		removeCoverMenuItem.Click += RemoveCurrentCover_Click;
		openCoverMenuItem.Name = "openCoverToolStripMenuItem";
		openCoverMenuItem.Size = new Size(185, 22);
		openCoverMenuItem.Text = "Open Cover";
		openCoverMenuItem.Click += OpenCurrentCover_Click;
		extractCoverMenuItem.Name = "extractCoverToolStripMenuItem";
		extractCoverMenuItem.Size = new Size(185, 22);
		extractCoverMenuItem.Text = "Extract cover";
		extractCoverMenuItem.Click += ExtractCover_Click;
		coverContextMenuSeparator.Name = "toolStripSeparator4";
		coverContextMenuSeparator.Size = new Size(182, 6);
		coverTypeMenuItem.Name = "coverTypeToolStripMenuItem";
		coverTypeMenuItem.Size = new Size(185, 22);
		coverTypeMenuItem.Text = "Cover Type";
		extractCoverSaveFileDialog.RestoreDirectory = true;
		controlToolTip.AutoPopDelay = 5000;
		controlToolTip.InitialDelay = 500;
		controlToolTip.ReshowDelay = 100;
		controlToolTip.ShowAlways = true;
		titleEncodingButton.Location = new Point(145, 0);
		titleEncodingButton.Margin = new Padding(5, 0, 0, 0);
		titleEncodingButton.Name = "btnETitle";
		titleEncodingButton.Size = new Size(30, 23);
		titleEncodingButton.TabIndex = 2;
		titleEncodingButton.Text = "A";
		controlToolTip.SetToolTip(titleEncodingButton, "Character Set");
		titleEncodingButton.UseVisualStyleBackColor = true;
		artistEncodingButton.Location = new Point(145, 0);
		artistEncodingButton.Margin = new Padding(5, 0, 0, 0);
		artistEncodingButton.Name = "btnEArtist";
		artistEncodingButton.Size = new Size(30, 23);
		artistEncodingButton.TabIndex = 4;
		artistEncodingButton.Text = "A";
		controlToolTip.SetToolTip(artistEncodingButton, "Character Set");
		artistEncodingButton.UseVisualStyleBackColor = true;
		albumEncodingButton.Location = new Point(145, 0);
		albumEncodingButton.Margin = new Padding(5, 0, 0, 0);
		albumEncodingButton.Name = "btnEAlbum";
		albumEncodingButton.Size = new Size(30, 23);
		albumEncodingButton.TabIndex = 6;
		albumEncodingButton.Text = "A";
		controlToolTip.SetToolTip(albumEncodingButton, "Character Set");
		albumEncodingButton.UseVisualStyleBackColor = true;
		yearEncodingButton.Location = new Point(145, 0);
		yearEncodingButton.Margin = new Padding(5, 0, 0, 0);
		yearEncodingButton.Name = "btnEYear";
		yearEncodingButton.Size = new Size(30, 23);
		yearEncodingButton.TabIndex = 8;
		yearEncodingButton.Text = "A";
		controlToolTip.SetToolTip(yearEncodingButton, "Character Set");
		yearEncodingButton.UseVisualStyleBackColor = true;
		trackEncodingButton.Location = new Point(127, 0);
		trackEncodingButton.Margin = new Padding(0);
		trackEncodingButton.Name = "btnETrack";
		trackEncodingButton.Size = new Size(0, 23);
		trackEncodingButton.TabIndex = 10;
		trackEncodingButton.Text = "A";
		controlToolTip.SetToolTip(trackEncodingButton, "Character Set");
		trackEncodingButton.UseVisualStyleBackColor = true;
		trackEncodingButton.Visible = false;
		discEncodingButton.Location = new Point(127, 0);
		discEncodingButton.Margin = new Padding(0);
		discEncodingButton.Name = "btnEDisc";
		discEncodingButton.Size = new Size(0, 23);
		discEncodingButton.TabIndex = 12;
		discEncodingButton.Text = "A";
		controlToolTip.SetToolTip(discEncodingButton, "Character Set");
		discEncodingButton.UseVisualStyleBackColor = true;
		discEncodingButton.Visible = false;
		genreEncodingButton.Location = new Point(145, 0);
		genreEncodingButton.Margin = new Padding(5, 0, 0, 0);
		genreEncodingButton.Name = "btnEGenre";
		genreEncodingButton.Size = new Size(30, 23);
		genreEncodingButton.TabIndex = 14;
		genreEncodingButton.Text = "A";
		controlToolTip.SetToolTip(genreEncodingButton, "Character Set");
		genreEncodingButton.UseVisualStyleBackColor = true;
		albumArtistEncodingButton.Location = new Point(145, 0);
		albumArtistEncodingButton.Margin = new Padding(5, 0, 0, 0);
		albumArtistEncodingButton.Name = "btnEAlbumartist";
		albumArtistEncodingButton.Size = new Size(30, 23);
		albumArtistEncodingButton.TabIndex = 16;
		albumArtistEncodingButton.Text = "A";
		controlToolTip.SetToolTip(albumArtistEncodingButton, "Character Set");
		albumArtistEncodingButton.UseVisualStyleBackColor = true;
		composerEncodingButton.Location = new Point(145, 0);
		composerEncodingButton.Margin = new Padding(5, 0, 0, 0);
		composerEncodingButton.Name = "btnEComposer";
		composerEncodingButton.Size = new Size(30, 23);
		composerEncodingButton.TabIndex = 18;
		composerEncodingButton.Text = "A";
		controlToolTip.SetToolTip(composerEncodingButton, "Character Set");
		composerEncodingButton.UseVisualStyleBackColor = true;
		lyricistEncodingButton.Location = new Point(145, 0);
		lyricistEncodingButton.Margin = new Padding(5, 0, 0, 0);
		lyricistEncodingButton.Name = "btnELyricist";
		lyricistEncodingButton.Size = new Size(30, 23);
		lyricistEncodingButton.TabIndex = 20;
		lyricistEncodingButton.Text = "A";
		controlToolTip.SetToolTip(lyricistEncodingButton, "Character Set");
		lyricistEncodingButton.UseVisualStyleBackColor = true;
		commentEncodingButton.Location = new Point(145, 0);
		commentEncodingButton.Margin = new Padding(5, 0, 0, 0);
		commentEncodingButton.Name = "btnEComment";
		commentEncodingButton.Size = new Size(30, 23);
		commentEncodingButton.TabIndex = 22;
		commentEncodingButton.Text = "A";
		controlToolTip.SetToolTip(commentEncodingButton, "Character Set");
		commentEncodingButton.UseVisualStyleBackColor = true;
		editLyricsButton.Location = new Point(145, 0);
		editLyricsButton.Margin = new Padding(5, 0, 0, 0);
		editLyricsButton.Name = "btnLyric";
		editLyricsButton.Size = new Size(30, 23);
		editLyricsButton.TabIndex = 24;
		editLyricsButton.Text = "...";
		controlToolTip.SetToolTip(editLyricsButton, "Edit lyric");
		editLyricsButton.UseVisualStyleBackColor = true;
		editLyricsButton.Click += EditLyrics_Click;
		lyricsEncodingButton.Location = new Point(180, 0);
		lyricsEncodingButton.Margin = new Padding(5, 0, 0, 0);
		lyricsEncodingButton.Name = "btnELyric";
		lyricsEncodingButton.Size = new Size(30, 23);
		lyricsEncodingButton.TabIndex = 25;
		lyricsEncodingButton.Text = "A";
		controlToolTip.SetToolTip(lyricsEncodingButton, "Character Set");
		lyricsEncodingButton.UseVisualStyleBackColor = true;
		overwriteCoverCheckBox.AutoSize = true;
		overwriteCoverCheckBox.Location = new Point(3, 88);
		overwriteCoverCheckBox.Margin = new Padding(0, 5, 0, 3);
		overwriteCoverCheckBox.Name = "cbOverwritePicture";
		overwriteCoverCheckBox.RightToLeft = RightToLeft.No;
		overwriteCoverCheckBox.Size = new Size(80, 18);
		overwriteCoverCheckBox.TabIndex = 30;
		overwriteCoverCheckBox.Text = "Overwrite";
		controlToolTip.SetToolTip(overwriteCoverCheckBox, "Overwrite existing image when adding");
		overwriteCoverCheckBox.UseVisualStyleBackColor = true;
		overwriteCoverCheckBox.CheckedChanged += SaveOverwriteCoverSetting_Click;
		fileListHeaderContextMenu.Items.AddRange(new ToolStripItem[1] { customizeColumnsContextMenuItem });
		fileListHeaderContextMenu.Name = "listViewColumnContextMenuStrip";
		fileListHeaderContextMenu.Size = new Size(175, 26);
		customizeColumnsContextMenuItem.Name = "customColumnsToolStripMenuItem";
		customizeColumnsContextMenuItem.Size = new Size(174, 22);
		customizeColumnsContextMenuItem.Text = "Custom Columns";
		customizeColumnsContextMenuItem.Click += ConfigureFileListColumns_Click;
		fileListItemContextMenu.Items.AddRange(new ToolStripItem[10] { saveTagsContextMenuItem, removeTagsContextMenuItem, readTagsContextMenuItem, characterSetContextMenuItem, tagHistoryContextMenuItem, fileListItemContextSeparator, renameFileContextMenuItem, removeItemsContextMenuItem, removeFilesContextMenuItem, openDirectoryContextMenuItem });
		fileListItemContextMenu.Name = "listViewItemContextMenuStrip";
		fileListItemContextMenu.Size = new Size(165, 208);
		saveTagsContextMenuItem.Enabled = false;
		saveTagsContextMenuItem.Name = "saveToolStripMenuItem1";
		saveTagsContextMenuItem.Size = new Size(164, 22);
		saveTagsContextMenuItem.Text = "Save tags";
		saveTagsContextMenuItem.Click += SaveTags_Click;
		removeTagsContextMenuItem.Enabled = false;
		removeTagsContextMenuItem.Name = "removeTagToolStripMenuItem1";
		removeTagsContextMenuItem.Size = new Size(164, 22);
		removeTagsContextMenuItem.Text = "Remove tags";
		removeTagsContextMenuItem.Click += ClearTags_Click;
		readTagsContextMenuItem.Enabled = false;
		readTagsContextMenuItem.Name = "readTagsToolStripMenuItem1";
		readTagsContextMenuItem.Size = new Size(164, 22);
		readTagsContextMenuItem.Text = "Read &tags";
		readTagsContextMenuItem.Click += RefreshSelectedFiles_Click;
		characterSetContextMenuItem.Enabled = false;
		characterSetContextMenuItem.Name = "characterSetToolStripMenuItem1";
		characterSetContextMenuItem.Size = new Size(164, 22);
		characterSetContextMenuItem.Text = "&Character Set";
		characterSetContextMenuItem.Click += EditAllTagFieldEncodings_Click;
		tagHistoryContextMenuItem.Enabled = false;
		tagHistoryContextMenuItem.Name = "tagsHistoryToolStripMenuItem1";
		tagHistoryContextMenuItem.Size = new Size(164, 22);
		tagHistoryContextMenuItem.Text = "Tags &History";
		tagHistoryContextMenuItem.Click += RestoreTagsFromHistory_Click;
		fileListItemContextSeparator.Name = "toolStripSeparator9";
		fileListItemContextSeparator.Size = new Size(161, 6);
		renameFileContextMenuItem.Enabled = false;
		renameFileContextMenuItem.Name = "renameFileToolStripMenuItem1";
		renameFileContextMenuItem.Size = new Size(164, 22);
		renameFileContextMenuItem.Text = "Rename";
		renameFileContextMenuItem.Click += BeginRenameSelectedFile_Click;
		removeItemsContextMenuItem.Enabled = false;
		removeItemsContextMenuItem.Name = "removeItemToolStripMenuItem1";
		removeItemsContextMenuItem.Size = new Size(164, 22);
		removeItemsContextMenuItem.Text = "Remove item";
		removeItemsContextMenuItem.Click += RemoveSelectedItemsFromList_Click;
		removeFilesContextMenuItem.Enabled = false;
		removeFilesContextMenuItem.Name = "removeFiletoolStripMenuItem1";
		removeFilesContextMenuItem.Size = new Size(164, 22);
		removeFilesContextMenuItem.Text = "Remove files";
		removeFilesContextMenuItem.Click += DeleteSelectedFiles_Click;
		openDirectoryContextMenuItem.Enabled = false;
		openDirectoryContextMenuItem.Name = "openDirectoryToolStripMenuItem1";
		openDirectoryContextMenuItem.Size = new Size(164, 22);
		openDirectoryContextMenuItem.Text = "Open directory";
		openDirectoryContextMenuItem.Click += RevealSelectedFileInExplorer_Click;
		selectionStatusUpdateTimer.Tick += SelectionStatusUpdateTimer_Tick;
		fileListStatusTimer.Tick += FileListStatusTimer_Tick;
		filterInputTimer.Interval = 500;
		filterInputTimer.Tick += FilterInputTimer_Tick;
		renamedFilesRefreshTimer.Interval = 500;
		renamedFilesRefreshTimer.Tick += RefreshRenamedFilesTimer_Tick;
		comboBoxSelectionResetTimer.Interval = 10;
		comboBoxSelectionResetTimer.Tick += ResetComboBoxSelectionTimer_Tick;
		notifyIcon.ContextMenuStrip = notifyContextMenu;
		notifyIcon.Text = "notifyIcon1";
		notifyIcon.Visible = true;
		notifyIcon.MouseClick += NotifyIcon_MouseClick;
		notifyContextMenu.Items.AddRange(new ToolStripItem[1] { notifyExitMenuItem });
		notifyContextMenu.Name = "notifyContextMenuStrip";
		notifyContextMenu.Size = new Size(97, 26);
		notifyExitMenuItem.Name = "notifyExitToolStripMenuItem";
		notifyExitMenuItem.Size = new Size(96, 22);
		notifyExitMenuItem.Text = "&Exit";
		mainSplitContainer.Dock = DockStyle.Fill;
		mainSplitContainer.FixedPanel = FixedPanel.Panel1;
		mainSplitContainer.Location = new Point(0, 50);
		mainSplitContainer.Name = "splitContainer1";
		mainSplitContainer.Panel1.Controls.Add(tagEditorPanel);
		mainSplitContainer.Panel1MinSize = 320;
		mainSplitContainer.Panel2.Controls.Add(fileListView);
		mainSplitContainer.Panel2.Controls.Add(fileFilterStatusStrip);
		mainSplitContainer.Panel2.Controls.Add(fileSummaryStatusStrip);
		mainSplitContainer.Panel2.SizeChanged += FileListPanel_SizeChanged;
		mainSplitContainer.Size = new Size(1589, 856);
		mainSplitContainer.SplitterDistance = 320;
		mainSplitContainer.SplitterWidth = 6;
		mainSplitContainer.TabIndex = 38;
		mainSplitContainer.SplitterMoved += RestartComboBoxSelectionResetTimer;
		tagEditorPanel.AutoScroll = true;
		tagEditorPanel.BackColor = SystemColors.Control;
		tagEditorPanel.Controls.Add(titleLabel);
		tagEditorPanel.Controls.Add(titleRowPanel);
		tagEditorPanel.Controls.Add(artistLabel);
		tagEditorPanel.Controls.Add(artistRowPanel);
		tagEditorPanel.Controls.Add(albumLabel);
		tagEditorPanel.Controls.Add(albumRowPanel);
		tagEditorPanel.Controls.Add(yearLabel);
		tagEditorPanel.Controls.Add(yearRowPanel);
		tagEditorPanel.Controls.Add(trackDiscGroupPanel);
		tagEditorPanel.Controls.Add(genreLabel);
		tagEditorPanel.Controls.Add(genreRowPanel);
		tagEditorPanel.Controls.Add(albumArtistLabel);
		tagEditorPanel.Controls.Add(albumArtistRowPanel);
		tagEditorPanel.Controls.Add(composerLabel);
		tagEditorPanel.Controls.Add(composerRowPanel);
		tagEditorPanel.Controls.Add(lyricistLabel);
		tagEditorPanel.Controls.Add(lyricistRowPanel);
		tagEditorPanel.Controls.Add(commentLabel);
		tagEditorPanel.Controls.Add(commentRowPanel);
		tagEditorPanel.Controls.Add(lyricsLabel);
		tagEditorPanel.Controls.Add(lyricsRowPanel);
		tagEditorPanel.Controls.Add(coverPanel);
		tagEditorPanel.Controls.Add(coverNavigationPanel);
		tagEditorPanel.Controls.Add(tagEditorBottomSpacerPanel);
		tagEditorPanel.Dock = DockStyle.Fill;
		tagEditorPanel.FlowDirection = FlowDirection.TopDown;
		tagEditorPanel.Location = new Point(0, 0);
		tagEditorPanel.Margin = new Padding(0);
		tagEditorPanel.Name = "flowLayoutPanel1";
		tagEditorPanel.Padding = new Padding(15);
		tagEditorPanel.Size = new Size(320, 856);
		tagEditorPanel.TabIndex = 0;
		tagEditorPanel.WrapContents = false;
		tagEditorPanel.SizeChanged += TagEditorPanel_SizeChanged;
		titleLabel.AutoSize = true;
		titleLabel.Location = new Point(18, 15);
		titleLabel.Name = "lblTitle";
		titleLabel.Size = new Size(39, 14);
		titleLabel.TabIndex = 0;
		titleLabel.Text = "Title: ";
		titleRowPanel.Controls.Add(titleComboBox);
		titleRowPanel.Controls.Add(titleEncodingButton);
		titleRowPanel.Location = new Point(18, 35);
		titleRowPanel.Margin = new Padding(3, 6, 3, 3);
		titleRowPanel.Name = "panelTitle";
		titleRowPanel.Size = new Size(284, 23);
		titleRowPanel.TabIndex = 26;
		titleComboBox.FormattingEnabled = true;
		titleComboBox.Location = new Point(0, 0);
		titleComboBox.Margin = new Padding(0);
		titleComboBox.Name = "cbTitle";
		titleComboBox.Size = new Size(140, 22);
		titleComboBox.TabIndex = 1;
		artistLabel.AutoSize = true;
		artistLabel.Location = new Point(18, 67);
		artistLabel.Margin = new Padding(3, 6, 3, 0);
		artistLabel.Name = "lblArtist";
		artistLabel.Size = new Size(44, 14);
		artistLabel.TabIndex = 2;
		artistLabel.Text = "Artist: ";
		artistRowPanel.Controls.Add(artistComboBox);
		artistRowPanel.Controls.Add(artistEncodingButton);
		artistRowPanel.Location = new Point(18, 87);
		artistRowPanel.Margin = new Padding(3, 6, 3, 3);
		artistRowPanel.Name = "panelArtist";
		artistRowPanel.Size = new Size(284, 23);
		artistRowPanel.TabIndex = 27;
		artistComboBox.FormattingEnabled = true;
		artistComboBox.Location = new Point(0, 0);
		artistComboBox.Margin = new Padding(0);
		artistComboBox.Name = "cbArtist";
		artistComboBox.Size = new Size(140, 22);
		artistComboBox.TabIndex = 3;
		albumLabel.AutoSize = true;
		albumLabel.Location = new Point(18, 119);
		albumLabel.Margin = new Padding(3, 6, 3, 0);
		albumLabel.Name = "lblAlbum";
		albumLabel.Size = new Size(49, 14);
		albumLabel.TabIndex = 4;
		albumLabel.Text = "Album: ";
		albumRowPanel.Controls.Add(albumComboBox);
		albumRowPanel.Controls.Add(albumEncodingButton);
		albumRowPanel.Location = new Point(18, 139);
		albumRowPanel.Margin = new Padding(3, 6, 3, 3);
		albumRowPanel.Name = "panelAlbum";
		albumRowPanel.Size = new Size(284, 23);
		albumRowPanel.TabIndex = 28;
		albumComboBox.FormattingEnabled = true;
		albumComboBox.Location = new Point(0, 0);
		albumComboBox.Margin = new Padding(0);
		albumComboBox.Name = "cbAlbum";
		albumComboBox.Size = new Size(140, 22);
		albumComboBox.TabIndex = 5;
		yearLabel.AutoSize = true;
		yearLabel.Location = new Point(18, 171);
		yearLabel.Margin = new Padding(3, 6, 3, 0);
		yearLabel.Name = "lblYear";
		yearLabel.Size = new Size(40, 14);
		yearLabel.TabIndex = 6;
		yearLabel.Text = "Year: ";
		yearRowPanel.Controls.Add(yearComboBox);
		yearRowPanel.Controls.Add(yearEncodingButton);
		yearRowPanel.Location = new Point(18, 191);
		yearRowPanel.Margin = new Padding(3, 6, 3, 3);
		yearRowPanel.Name = "panelYear";
		yearRowPanel.Size = new Size(284, 23);
		yearRowPanel.TabIndex = 29;
		yearComboBox.FormattingEnabled = true;
		yearComboBox.Location = new Point(0, 0);
		yearComboBox.Margin = new Padding(0);
		yearComboBox.Name = "cbYear";
		yearComboBox.Size = new Size(140, 22);
		yearComboBox.TabIndex = 7;
		trackDiscGroupPanel.Controls.Add(trackColumnPanel);
		trackDiscGroupPanel.Controls.Add(discColumnPanel);
		trackDiscGroupPanel.Location = new Point(18, 223);
		trackDiscGroupPanel.Margin = new Padding(3, 6, 3, 3);
		trackDiscGroupPanel.Name = "panelTrackDisc";
		trackDiscGroupPanel.Size = new Size(284, 42);
		trackDiscGroupPanel.TabIndex = 30;
		trackColumnPanel.Controls.Add(trackLabel);
		trackColumnPanel.Controls.Add(trackRowPanel);
		trackColumnPanel.FlowDirection = FlowDirection.TopDown;
		trackColumnPanel.Location = new Point(0, 0);
		trackColumnPanel.Margin = new Padding(0);
		trackColumnPanel.Name = "panelTrack1";
		trackColumnPanel.Size = new Size(142, 43);
		trackColumnPanel.TabIndex = 40;
		trackLabel.AutoSize = true;
		trackLabel.Location = new Point(0, 0);
		trackLabel.Margin = new Padding(0);
		trackLabel.Name = "lblTrack";
		trackLabel.Size = new Size(45, 14);
		trackLabel.TabIndex = 31;
		trackLabel.Text = "Track: ";
		trackRowPanel.Controls.Add(trackComboBox);
		trackRowPanel.Controls.Add(trackEncodingButton);
		trackRowPanel.Location = new Point(0, 20);
		trackRowPanel.Margin = new Padding(0, 6, 0, 0);
		trackRowPanel.Name = "panelTrack";
		trackRowPanel.Size = new Size(142, 23);
		trackRowPanel.TabIndex = 32;
		trackComboBox.FormattingEnabled = true;
		trackComboBox.Location = new Point(0, 0);
		trackComboBox.Margin = new Padding(0);
		trackComboBox.Name = "cbTrack";
		trackComboBox.Size = new Size(127, 22);
		trackComboBox.TabIndex = 9;
		discColumnPanel.Controls.Add(discLabel);
		discColumnPanel.Controls.Add(discRowPanel);
		discColumnPanel.FlowDirection = FlowDirection.TopDown;
		discColumnPanel.Location = new Point(142, 0);
		discColumnPanel.Margin = new Padding(0);
		discColumnPanel.Name = "panelDisc1";
		discColumnPanel.Size = new Size(142, 43);
		discColumnPanel.TabIndex = 41;
		discLabel.AutoSize = true;
		discLabel.Location = new Point(0, 0);
		discLabel.Margin = new Padding(0);
		discLabel.Name = "lblDisc";
		discLabel.Size = new Size(36, 14);
		discLabel.TabIndex = 32;
		discLabel.Text = "Disc: ";
		discRowPanel.Controls.Add(discComboBox);
		discRowPanel.Controls.Add(discEncodingButton);
		discRowPanel.Location = new Point(0, 20);
		discRowPanel.Margin = new Padding(0, 6, 0, 0);
		discRowPanel.Name = "panelDisc";
		discRowPanel.Size = new Size(142, 23);
		discRowPanel.TabIndex = 33;
		discComboBox.FormattingEnabled = true;
		discComboBox.Location = new Point(0, 0);
		discComboBox.Margin = new Padding(0);
		discComboBox.Name = "cbDisc";
		discComboBox.Size = new Size(127, 22);
		discComboBox.TabIndex = 11;
		genreLabel.AutoSize = true;
		genreLabel.Location = new Point(18, 274);
		genreLabel.Margin = new Padding(3, 6, 3, 0);
		genreLabel.Name = "lblGenre";
		genreLabel.Size = new Size(48, 14);
		genreLabel.TabIndex = 12;
		genreLabel.Text = "Genre: ";
		genreRowPanel.Controls.Add(genreComboBox);
		genreRowPanel.Controls.Add(genreEncodingButton);
		genreRowPanel.Location = new Point(18, 294);
		genreRowPanel.Margin = new Padding(3, 6, 3, 3);
		genreRowPanel.Name = "panelGenre";
		genreRowPanel.Size = new Size(284, 23);
		genreRowPanel.TabIndex = 32;
		genreComboBox.FormattingEnabled = true;
		genreComboBox.Location = new Point(0, 0);
		genreComboBox.Margin = new Padding(0);
		genreComboBox.Name = "cbGenre";
		genreComboBox.Size = new Size(140, 22);
		genreComboBox.TabIndex = 13;
		albumArtistLabel.AutoSize = true;
		albumArtistLabel.Location = new Point(18, 326);
		albumArtistLabel.Margin = new Padding(3, 6, 3, 0);
		albumArtistLabel.Name = "lblAlbumartist";
		albumArtistLabel.Size = new Size(76, 14);
		albumArtistLabel.TabIndex = 14;
		albumArtistLabel.Text = "Albumartist: ";
		albumArtistRowPanel.Controls.Add(albumArtistComboBox);
		albumArtistRowPanel.Controls.Add(albumArtistEncodingButton);
		albumArtistRowPanel.Location = new Point(18, 346);
		albumArtistRowPanel.Margin = new Padding(3, 6, 3, 3);
		albumArtistRowPanel.Name = "panelAlbumartist";
		albumArtistRowPanel.Size = new Size(284, 23);
		albumArtistRowPanel.TabIndex = 33;
		albumArtistComboBox.FormattingEnabled = true;
		albumArtistComboBox.Location = new Point(0, 0);
		albumArtistComboBox.Margin = new Padding(0);
		albumArtistComboBox.Name = "cbAlbumartist";
		albumArtistComboBox.Size = new Size(140, 22);
		albumArtistComboBox.TabIndex = 15;
		composerLabel.AutoSize = true;
		composerLabel.Location = new Point(18, 378);
		composerLabel.Margin = new Padding(3, 6, 3, 0);
		composerLabel.Name = "lblComposer";
		composerLabel.Size = new Size(69, 14);
		composerLabel.TabIndex = 16;
		composerLabel.Text = "Composer: ";
		composerRowPanel.Controls.Add(composerComboBox);
		composerRowPanel.Controls.Add(composerEncodingButton);
		composerRowPanel.Location = new Point(18, 398);
		composerRowPanel.Margin = new Padding(3, 6, 3, 3);
		composerRowPanel.Name = "panelComposer";
		composerRowPanel.Size = new Size(284, 23);
		composerRowPanel.TabIndex = 34;
		composerComboBox.FormattingEnabled = true;
		composerComboBox.Location = new Point(0, 0);
		composerComboBox.Margin = new Padding(0);
		composerComboBox.Name = "cbComposer";
		composerComboBox.Size = new Size(140, 22);
		composerComboBox.TabIndex = 17;
		lyricistLabel.AutoSize = true;
		lyricistLabel.Location = new Point(18, 430);
		lyricistLabel.Margin = new Padding(3, 6, 3, 0);
		lyricistLabel.Name = "lblLyricist";
		lyricistLabel.Size = new Size(51, 14);
		lyricistLabel.TabIndex = 39;
		lyricistLabel.Text = "Lyricist: ";
		lyricistRowPanel.Controls.Add(lyricistComboBox);
		lyricistRowPanel.Controls.Add(lyricistEncodingButton);
		lyricistRowPanel.Location = new Point(18, 450);
		lyricistRowPanel.Margin = new Padding(3, 6, 3, 3);
		lyricistRowPanel.Name = "panelLyricist";
		lyricistRowPanel.Size = new Size(284, 23);
		lyricistRowPanel.TabIndex = 35;
		lyricistComboBox.FormattingEnabled = true;
		lyricistComboBox.Location = new Point(0, 0);
		lyricistComboBox.Margin = new Padding(0);
		lyricistComboBox.Name = "cbLyricist";
		lyricistComboBox.Size = new Size(140, 22);
		lyricistComboBox.TabIndex = 19;
		commentLabel.AutoSize = true;
		commentLabel.Location = new Point(18, 482);
		commentLabel.Margin = new Padding(3, 6, 3, 0);
		commentLabel.Name = "lblComment";
		commentLabel.Size = new Size(68, 14);
		commentLabel.TabIndex = 18;
		commentLabel.Text = "Comment: ";
		commentRowPanel.Controls.Add(commentComboBox);
		commentRowPanel.Controls.Add(commentEncodingButton);
		commentRowPanel.Location = new Point(18, 502);
		commentRowPanel.Margin = new Padding(3, 6, 3, 3);
		commentRowPanel.Name = "panelComment";
		commentRowPanel.Size = new Size(284, 23);
		commentRowPanel.TabIndex = 36;
		commentComboBox.FormattingEnabled = true;
		commentComboBox.Location = new Point(0, 0);
		commentComboBox.Margin = new Padding(0);
		commentComboBox.Name = "cbComment";
		commentComboBox.Size = new Size(140, 22);
		commentComboBox.TabIndex = 21;
		lyricsLabel.AutoSize = true;
		lyricsLabel.Location = new Point(18, 534);
		lyricsLabel.Margin = new Padding(3, 6, 3, 0);
		lyricsLabel.Name = "lblLyric";
		lyricsLabel.Size = new Size(39, 14);
		lyricsLabel.TabIndex = 21;
		lyricsLabel.Text = "Lyric: ";
		lyricsRowPanel.Controls.Add(lyricsComboBox);
		lyricsRowPanel.Controls.Add(editLyricsButton);
		lyricsRowPanel.Controls.Add(lyricsEncodingButton);
		lyricsRowPanel.Location = new Point(18, 554);
		lyricsRowPanel.Margin = new Padding(3, 6, 3, 3);
		lyricsRowPanel.Name = "panelLyric";
		lyricsRowPanel.Size = new Size(284, 23);
		lyricsRowPanel.TabIndex = 37;
		lyricsComboBox.FormattingEnabled = true;
		lyricsComboBox.Location = new Point(0, 0);
		lyricsComboBox.Margin = new Padding(0);
		lyricsComboBox.Name = "cbLyric";
		lyricsComboBox.Size = new Size(140, 22);
		lyricsComboBox.TabIndex = 23;
		coverPanel.BackColor = SystemColors.Control;
		coverPanel.Controls.Add(coverPictureBox);
		coverPanel.Controls.Add(statusLabelsPanel);
		coverPanel.Location = new Point(18, 595);
		coverPanel.Margin = new Padding(3, 15, 3, 3);
		coverPanel.Name = "panelPicture";
		coverPanel.Size = new Size(284, 163);
		coverPanel.TabIndex = 37;
		coverPictureBox.BackColor = SystemColors.Window;
		coverPictureBox.BorderStyle = BorderStyle.Fixed3D;
		coverPictureBox.Location = new Point(0, 0);
		coverPictureBox.Margin = new Padding(0);
		coverPictureBox.Name = "picBoxPicture";
		coverPictureBox.Size = new Size(163, 163);
		coverPictureBox.SizeMode = PictureBoxSizeMode.CenterImage;
		coverPictureBox.TabIndex = 24;
		coverPictureBox.TabStop = false;
		coverPictureBox.MouseUp += CoverPicture_MouseUp;
		statusLabelsPanel.Controls.Add(coverMimeTypeLabel);
		statusLabelsPanel.Controls.Add(coverDimensionsLabel);
		statusLabelsPanel.Controls.Add(coverFileSizeLabel);
		statusLabelsPanel.Controls.Add(coverPictureTypeLabel);
		statusLabelsPanel.Controls.Add(overwriteCoverCheckBox);
		statusLabelsPanel.Dock = DockStyle.Fill;
		statusLabelsPanel.FlowDirection = FlowDirection.TopDown;
		statusLabelsPanel.Location = new Point(163, 0);
		statusLabelsPanel.Margin = new Padding(0);
		statusLabelsPanel.Name = "flowLayoutPanel2";
		statusLabelsPanel.Padding = new Padding(3);
		statusLabelsPanel.Size = new Size(121, 163);
		statusLabelsPanel.TabIndex = 21;
		statusLabelsPanel.WrapContents = false;
		statusLabelsPanel.SizeChanged += StatusLabelsPanel_SizeChanged;
		statusLabelsPanel.SetFlowBreak(coverMimeTypeLabel, value: true);
		coverMimeTypeLabel.Location = new Point(6, 3);
		coverMimeTypeLabel.Name = "lblPicMimeType";
		coverMimeTypeLabel.Size = new Size(115, 20);
		coverMimeTypeLabel.TabIndex = 0;
		coverMimeTypeLabel.TextAlign = ContentAlignment.MiddleCenter;
		statusLabelsPanel.SetFlowBreak(coverDimensionsLabel, value: true);
		coverDimensionsLabel.Location = new Point(6, 23);
		coverDimensionsLabel.Name = "lblPicRatio";
		coverDimensionsLabel.Size = new Size(115, 20);
		coverDimensionsLabel.TabIndex = 1;
		coverDimensionsLabel.TextAlign = ContentAlignment.MiddleCenter;
		statusLabelsPanel.SetFlowBreak(coverFileSizeLabel, value: true);
		coverFileSizeLabel.Location = new Point(6, 43);
		coverFileSizeLabel.Name = "lblPicSize";
		coverFileSizeLabel.Size = new Size(115, 20);
		coverFileSizeLabel.TabIndex = 2;
		coverFileSizeLabel.TextAlign = ContentAlignment.MiddleCenter;
		statusLabelsPanel.SetFlowBreak(coverPictureTypeLabel, value: true);
		coverPictureTypeLabel.Location = new Point(6, 63);
		coverPictureTypeLabel.Name = "lblPicType";
		coverPictureTypeLabel.Size = new Size(115, 20);
		coverPictureTypeLabel.TabIndex = 3;
		coverPictureTypeLabel.TextAlign = ContentAlignment.MiddleCenter;
		coverNavigationPanel.AutoSize = true;
		coverNavigationPanel.Controls.Add(previousCoverButton);
		coverNavigationPanel.Controls.Add(coverIndexLabel);
		coverNavigationPanel.Controls.Add(nextCoverButton);
		coverNavigationPanel.Location = new Point(18, 764);
		coverNavigationPanel.Name = "flowLayoutPanel3";
		coverNavigationPanel.Size = new Size(168, 29);
		coverNavigationPanel.TabIndex = 24;
		coverNavigationPanel.Visible = false;
		previousCoverButton.Location = new Point(3, 3);
		previousCoverButton.Name = "btnPrePic";
		previousCoverButton.Size = new Size(30, 23);
		previousCoverButton.TabIndex = 0;
		previousCoverButton.Text = "<";
		previousCoverButton.UseVisualStyleBackColor = true;
		previousCoverButton.Click += PreviousCover_Click;
		coverIndexLabel.Location = new Point(39, 3);
		coverIndexLabel.Margin = new Padding(3, 3, 3, 0);
		coverIndexLabel.Name = "lblPicIdx";
		coverIndexLabel.Size = new Size(90, 23);
		coverIndexLabel.TabIndex = 1;
		coverIndexLabel.Text = "1/1";
		coverIndexLabel.TextAlign = ContentAlignment.MiddleCenter;
		nextCoverButton.Location = new Point(135, 3);
		nextCoverButton.Name = "btnNextPic";
		nextCoverButton.Size = new Size(30, 23);
		nextCoverButton.TabIndex = 2;
		nextCoverButton.Text = ">";
		nextCoverButton.UseVisualStyleBackColor = true;
		nextCoverButton.Click += NextCover_Click;
		tagEditorBottomSpacerPanel.Location = new Point(15, 796);
		tagEditorBottomSpacerPanel.Margin = new Padding(0);
		tagEditorBottomSpacerPanel.Name = "panelDummy";
		tagEditorBottomSpacerPanel.Size = new Size(143, 20);
		tagEditorBottomSpacerPanel.TabIndex = 38;
		fileListView.AllowDrop = true;
		fileListView.Dock = DockStyle.Fill;
		fileListView.VirtualMode = true;
		fileListView.AllowUserToAddRows = false;
		fileListView.AllowUserToDeleteRows = false;
		fileListView.AllowUserToResizeRows = false;
		fileListView.RowHeadersVisible = false;
		fileListView.MultiSelect = true;
		fileListView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
		fileListView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
		fileListView.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.None;
		fileListView.EditMode = DataGridViewEditMode.EditProgrammatically;
		fileListView.ShowCellToolTips = false;
		fileListView.ClipboardCopyMode = DataGridViewClipboardCopyMode.Disable;
		fileListView.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
		fileListView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
		ApplyFileListVisualStyle();
		fileListView.Location = new Point(0, 0);
		fileListView.Margin = new Padding(0);
		fileListView.Name = "listView1";
		fileListView.Size = new Size(1263, 806);
		fileListView.TabIndex = 31;
		fileListView.CellValueNeeded += FileList_CellValueNeeded;
		fileListView.CellFormatting += FileList_CellFormatting;
		fileListView.CellPainting += FileList_CellPainting;
		fileListView.SelectionChanged += FileList_SelectionChanged;
		fileListView.ColumnHeaderMouseClick += FileList_ColumnHeaderMouseClick;
		fileListView.CellMouseDown += FileList_CellMouseDown;
		fileListView.CellBeginEdit += FileList_CellBeginEdit;
		fileListView.CellEndEdit += FileList_CellEndEdit;
		fileListView.CellValidating += FileList_CellValidating;
		fileListView.CellValuePushed += FileList_CellValuePushed;
		fileListView.EditingControlShowing += FileList_EditingControlShowing;
		fileListView.DragDrop += FileList_DragDrop;
		fileListView.DragEnter += FileList_DragEnter;
		fileListView.DragLeave += FileList_DragLeave;
		fileFilterStatusStrip.Items.AddRange(new ToolStripItem[3] { filterStatusLabel, filterTextBox, filterTypeDropDownButton });
		fileFilterStatusStrip.Location = new Point(0, 806);
		fileFilterStatusStrip.Name = "statusStrip2";
		fileFilterStatusStrip.Size = new Size(1263, 27);
		fileFilterStatusStrip.SizingGrip = false;
		fileFilterStatusStrip.TabIndex = 32;
		fileFilterStatusStrip.Text = "statusStrip2";
		fileFilterStatusStrip.SizeChanged += FilterBar_SizeChanged;
		filterStatusLabel.Name = "filterToolStripStatusLabel";
		filterStatusLabel.Size = new Size(39, 22);
		filterStatusLabel.Text = "Filter:";
		filterTextBox.AutoSize = false;
		filterTextBox.Margin = new Padding(1, 3, 1, 3);
		filterTextBox.Name = "filterToolStripTextBox";
		filterTextBox.Size = new Size(500, 21);
		filterTextBox.TextChanged += FilterInput_TextChanged;
		filterTypeDropDownButton.AutoSize = false;
		filterTypeDropDownButton.DisplayStyle = ToolStripItemDisplayStyle.Text;
		filterTypeDropDownButton.Image = (Image)componentResourceManager.GetObject("filterToolStripDropDownButton.Image");
		filterTypeDropDownButton.ImageTransparentColor = Color.Magenta;
		filterTypeDropDownButton.Margin = new Padding(0, 3, 0, 3);
		filterTypeDropDownButton.Name = "filterToolStripDropDownButton";
		filterTypeDropDownButton.Size = new Size(100, 21);
		fileSummaryStatusStrip.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
		fileSummaryStatusStrip.Items.AddRange(new ToolStripItem[3] { selectedFilesStatusLabel, fileSummaryStatusSeparator, totalFilesStatusLabel });
		fileSummaryStatusStrip.Location = new Point(0, 833);
		fileSummaryStatusStrip.Name = "statusStrip1";
		fileSummaryStatusStrip.Size = new Size(1263, 23);
		fileSummaryStatusStrip.TabIndex = 1;
		fileSummaryStatusStrip.Text = "statusStrip1";
		selectedFilesStatusLabel.AutoSize = false;
		selectedFilesStatusLabel.Name = "seledFilesToolStripStatusLabel";
		selectedFilesStatusLabel.Size = new Size(190, 18);
		selectedFilesStatusLabel.Text = "0 (00:00:00 0Byte) ";
		selectedFilesStatusLabel.TextAlign = ContentAlignment.MiddleLeft;
		fileSummaryStatusSeparator.BackColor = SystemColors.Control;
		fileSummaryStatusSeparator.Name = "toolSeparator1";
		fileSummaryStatusSeparator.Size = new Size(6, 23);
		totalFilesStatusLabel.Name = "allFilesToolStripStatusLabel";
		totalFilesStatusLabel.Size = new Size(118, 18);
		totalFilesStatusLabel.Text = "0 (00:00:00 0Byte) ";
		totalFilesStatusLabel.TextAlign = ContentAlignment.MiddleLeft;
		base.AutoScaleDimensions = new SizeF(96f, 96f);
		base.AutoScaleMode = AutoScaleMode.Dpi;
		base.ClientSize = new Size(1589, 906);
		Controls.Add(mainSplitContainer);
		base.Controls.Add(mainToolStrip);
		base.Controls.Add(mainMenuStrip);
		Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
		IsMdiContainer = true;
		base.MainMenuStrip = mainMenuStrip;
		base.Name = "FormMain";
		Text = "Music Tag";
		base.SizeChanged += MainForm_SizeChanged;
		mainMenuStrip.ResumeLayout(performLayout: false);
		mainMenuStrip.PerformLayout();
		mainToolStrip.ResumeLayout(performLayout: false);
		mainToolStrip.PerformLayout();
		coverContextMenu.ResumeLayout(performLayout: false);
		fileListHeaderContextMenu.ResumeLayout(performLayout: false);
		fileListItemContextMenu.ResumeLayout(performLayout: false);
		notifyContextMenu.ResumeLayout(performLayout: false);
		mainSplitContainer.Panel1.ResumeLayout(performLayout: false);
		mainSplitContainer.Panel2.ResumeLayout(performLayout: false);
		mainSplitContainer.Panel2.PerformLayout();
		((ISupportInitialize)mainSplitContainer).EndInit();
		mainSplitContainer.ResumeLayout(performLayout: false);
		tagEditorPanel.ResumeLayout(performLayout: false);
		tagEditorPanel.PerformLayout();
		titleRowPanel.ResumeLayout(performLayout: false);
		artistRowPanel.ResumeLayout(performLayout: false);
		albumRowPanel.ResumeLayout(performLayout: false);
		yearRowPanel.ResumeLayout(performLayout: false);
		trackDiscGroupPanel.ResumeLayout(performLayout: false);
		trackColumnPanel.ResumeLayout(performLayout: false);
		trackColumnPanel.PerformLayout();
		trackRowPanel.ResumeLayout(performLayout: false);
		discColumnPanel.ResumeLayout(performLayout: false);
		discColumnPanel.PerformLayout();
		discRowPanel.ResumeLayout(performLayout: false);
		genreRowPanel.ResumeLayout(performLayout: false);
		albumArtistRowPanel.ResumeLayout(performLayout: false);
		composerRowPanel.ResumeLayout(performLayout: false);
		lyricistRowPanel.ResumeLayout(performLayout: false);
		commentRowPanel.ResumeLayout(performLayout: false);
		lyricsRowPanel.ResumeLayout(performLayout: false);
		coverPanel.ResumeLayout(performLayout: false);
		((ISupportInitialize)coverPictureBox).EndInit();
		statusLabelsPanel.ResumeLayout(performLayout: false);
		statusLabelsPanel.PerformLayout();
		coverNavigationPanel.ResumeLayout(performLayout: false);
		fileFilterStatusStrip.ResumeLayout(performLayout: false);
		fileFilterStatusStrip.PerformLayout();
		fileSummaryStatusStrip.ResumeLayout(performLayout: false);
		fileSummaryStatusStrip.PerformLayout();
		ResumeLayout(performLayout: false);
		PerformLayout();
	}
}
